<a href="https://colab.research.google.com/github/Tan-Jiahua/migration-time-correction/blob/main/MTcorrection_20210427.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import io

In [2]:
# Load the CSV file
from google.colab import files
uploaded = files.upload()
# To remove the data, we can use:
# !rm rawdata.csv

Saving rawdata.csv to rawdata.csv

In [3]:
# Obtain column names of this CSV file
data = pd.read_csv('rawdata.csv')    
data_top = data.head()
column_list = list(data_top.columns)
print(data_top)
print('')
print('Get the column names of this CSV file:')
print(column_list)

   TransitionNum     Q1    Q3     MT        Area     Sample
0              0  115.3  87.1  10.88  11070312.0  01_G1_1_U
1              0  115.3  87.1  13.90  23532902.0  02_G1_2_U
2              0  115.3  87.1  10.60   9611286.0  03_G1_3_U
3              0  115.3  87.1  11.63   6360009.0  04_G2_1_U
4              0  115.3  87.1  12.56  11871461.0  05_G2_2_U

Get the column names of this CSV file:
['TransitionNum', 'Q1', 'Q3', 'MT', 'Area', 'Sample']

In [4]:
# Global functions

# Obtain the largest transition number in all samples
def get_max_transition_num(dfs):
    max_transition_num=0
    for i in range(1,len(dfs)+1):
        if dfs[i]['Transition'].max()>max_transition_num:
            max_transition_num=dfs[i]['Transition'].max()
    return max_transition_num

# Get the number of samples in df format
def get_num_of_samples_for_df(df):
    num_of_samples=0
    while str(num_of_samples+1)+'_time' in df.columns:
        num_of_samples+=1
    return num_of_samples

def get_num_of_peaks_in_a_row(df):
    peak_no=1
    num_of_peaks=0
    while str(peak_no)+'_time' in df.index:
        if pd.notnull(df[str(peak_no)+'_time']):
            num_of_peaks+=1
        peak_no+=1
    return num_of_peaks

#Attach average migration time and its relative standard deviation
#If there is corrected migration time values named 'n_time_4markers' (n is sample number), the corrected values 
#will be used in calculation.
#Otherwise, the original migration time will be used.
def with_avgMT_and_RSD(df_input):
    df=df_input.copy()
    is_Series=False
    if isinstance(df,pd.Series):
        df=df.to_frame().T
        is_Series=True
    num_of_samples=get_num_of_samples_for_df(df)
    df_time=df.drop(df.columns,axis='columns')
    df_stat_value=df.drop(df.columns,axis='columns')
    if str(num_of_samples)+'_time_6markers' in df.columns:
        for i in range(0,num_of_samples):
            df_time[str(i+1)+'_time_6markers']=df[str(i+1)+'_time_6markers']
    elif str(num_of_samples)+'_time_4markers' in df.columns:
        for i in range(0,num_of_samples):
            df_time[str(i+1)+'_time_4markers']=df[str(i+1)+'_time_4markers']
    else:
        for i in range(0,num_of_samples):
            df_time[str(i+1)+'_time']=df[str(i+1)+'_time']
    df['Average_MT']=df_time.mean(axis=1)
    df['std']=df_time.std(axis=1,ddof=0)
    df['RSD(%)']=df['std']/df['Average_MT']*100
    df=df.drop(['std'],axis=1)
    if is_Series:
        df=df.squeeze()
    return df

#Select 'idx' representing a peak in 'transition' labelled as 'label'
#If the peak does not exist in variable 'chart_from_idx_to_transition_and_label_inIntermediatePhase', return -1
def transition_and_label_to_idx(chart_from_idx_to_transition_and_label_inIntermediatePhase,transition,label):
    num_of_idx=chart_from_idx_to_transition_and_label_inIntermediatePhase.shape[0]
    idx=0
    while idx!=num_of_idx \
        and (chart_from_idx_to_transition_and_label_inIntermediatePhase['Transition'][idx]!=transition or \
        chart_from_idx_to_transition_and_label_inIntermediatePhase['Label'][idx]!=label):
        idx+=1
    if idx==num_of_idx:
        print('Peak '+str(transition)+label+' is not in variable dfs')
        return -1
    return idx

In [5]:
# Function 1: process the uploaded CSV file and return the individual dataset for each sample
def F1_create_datasets(csv_name, column_name_for_transition, column_name_for_precursor_ion, 
                   column_name_for_product_ion, column_name_for_time, 
                   column_name_for_area, column_name_for_sample):
    csv_file = csv_name
    sample_column = column_name_for_sample
    area_column = column_name_for_area
    time_column = column_name_for_time
    Q1 = column_name_for_precursor_ion
    Q3 = column_name_for_product_ion
    transition_column = column_name_for_transition
    data = io.BytesIO(uploaded[csv_name]) 
    df_input = pd.read_csv(data)
    df = df_input.fillna(0) 
    df_no_zero = df[df[area_column]>0].reset_index(drop=True)
    sample_name = df_no_zero[sample_column].unique()
    print('There are {} samples.'.format(len(sample_name)))
    print('')
    print('The peak numbers of each sample are as follow:')
    print (df_no_zero[sample_column].value_counts())
    print('')
    
    sample_number = len(sample_name)
    df_no_zero['sample'] = df_no_zero[sample_column].apply(lambda x:x[:2]).tolist()
    df2 = df_no_zero.drop([sample_column], axis=1)
    dfs={}
    types={}
    i=0
    j=1
    for i in range(sample_number):
        i_str = str(i+1)       
        i_str_2digits = i_str.zfill(2)
        print('The dataset of sample {} is created.'.format(j))
        dfs[j] = df2.groupby(['sample']).get_group(i_str_2digits).reset_index(drop=True)
        dfs[j] = dfs[j].drop(columns=[Q1, Q3,'sample'])
        dfs[j] = dfs[j].rename(columns={transition_column:'Transition',
                                        time_column: i_str+'_time', 
                                        area_column:i_str+'_area'}).reset_index(drop=True)
        i += 1
        j += 1
    print('')
    print('Function 1 is completed. Datasets can be viewed by using "print(dfs)" or "print(dfs[i].head())".')
    return dfs

In [6]:
# Using Function 1
csv_name = 'rawdata.csv'
column_name_for_transition = column_list[0]
column_name_for_precursor_ion = column_list[1]
column_name_for_product_ion = column_list[2]
column_name_for_time = column_list[3]
column_name_for_area = column_list[4]
column_name_for_sample = column_list[5]

dfs = F1_create_datasets(csv_name, column_name_for_transition, column_name_for_precursor_ion,
                         column_name_for_product_ion, column_name_for_time,
                         column_name_for_area, column_name_for_sample)

There are 32 samples.

The peak numbers of each sample are as follow:
14_G5_2_U    381
29_G2_3_R    357
23_G3_3_S    340
22_G3_2_S    339
32_G4_3_R    336
28_G2_2_R    335
31_G4_2_R    329
27_G2_1_R    319
08_G3_2_U    317
17_G1_3_S    310
01_G1_1_U    293
16_G1_2_S    283
21_G3_1_S    281
09_G3_3_U    275
30_G4_1_R    272
06_G2_3_U    272
15_G1_1_S    268
02_G1_2_U    262
07_G3_1_U    258
05_G2_2_U    258
24_G4_1_S    249
10_G4_1_U    249
18_G2_1_S    246
13_G5_1_U    245
04_G2_1_U    242
19_G2_2_S    234
25_G4_2_S    226
12_G4_3_U    220
03_G1_3_U    219
11_G4_2_U    207
26_G4_3_S    192
20_G2_3_S    173
Name: Sample, dtype: int64

The dataset of sample 1 is created.
The dataset of sample 2 is created.
The dataset of sample 3 is created.
The dataset of sample 4 is created.
The dataset of sample 5 is created.
The dataset of sample 6 is created.
The dataset of sample 7 is created.
The dataset of sample 8 is created.
The dataset of sample 9 is created.
The dataset of sample 10 is created.
The dataset of sample 11 is created.
The dataset of sample 12 is created.
The dataset of sample 13 is created.
The dataset of sample 14 is created.
The dataset of sample 15 is created.
The dataset of sample 16 is created.
The dataset of sample 17 is created.
The dataset of sample 18 is created.
The dataset of sample 19 is created.
The dataset of sample 20 is created.
The dataset of sample 21 is created.
The dataset of sample 22 is created.
The dataset of sample 23 is created.
The dataset of sample 24 is created.
The dataset of sample 25 is created.
The dataset of sample 26 is created.
The dataset of sample 27 is created.
The dataset of sample 28 is created.
The dataset of sample 29 is created.
The dataset of sample 30 is created.
The dataset of sample 31 is created.
The dataset of sample 32 is created.

Function 1 is completed. Datasets can be viewed by using "print(dfs)" or "print(dfs[i].head())".

In [7]:
# Check one of the sample datasets
print(dfs[32].head(20))

    Transition  32_time     32_area
0            0    12.94   6642411.0
1            1    13.12   2675259.0
2            1    14.31    104233.0
3            2     6.02     44876.0
4            3    12.22    290774.0
5            5     7.61    150544.0
6            6    13.12     47704.0
7            8     9.57     30822.0
8           10    12.56     86985.0
9           11    12.94    140276.0
10          12    12.88  30245364.0
11          13    12.84    244068.0
12          13    20.92     42080.0
13          14     8.88    988073.0
14          15    13.12    537786.0
15          16    13.16     81345.0
16          17    28.03     34595.0
17          17    12.66     15902.0
18          18    13.22    289318.0
19          18    11.91     49571.0

In [8]:
#Global functions

#Check and remove unqualified peak based on allowed EORMT value
#df_input with index named by 'Transition', ('Transition','Label') or None are acceptable
#Average migration time value is required in df_input (should be prepocessesed by function with_avgMT_and_RSD)

def check_and_correct(df_input,allowed_EORMT,location):
    df=df_input.copy()

    if '1_time_6markers' in df.columns:
        time_suffix='_time_6markers'
    elif '1_time_4markers' in df.columns:
        time_suffix='_time_4markers'
    else:
        time_suffix='_time'

    axes_name=df.axes[0].name#When index is 'Transition'
    axes_names=df.axes[0].names#When index is ('Transition,'Label')
    df=df.sort_values(by='Average_MT').reset_index()

    if location=='step_2': 
        df['remove']=False
    else:#only available when 
        df['earlyList']=''
        df['earlyList']=df['earlyList'].apply(list)
        df['lateList']=''
        df['lateList']=df['lateList'].apply(list)

    num_of_samples=get_num_of_samples_for_df(df)
    for j in range(1,num_of_samples+1):
        if df[str(j)+time_suffix].count()<=3:
            continue

        #The firstly analyzed peak is the first peak
        peak1_is_first_peak=True
        
        for i in range(0,df.shape[0]-1):
            t_peak1 = float(df[str(j)+time_suffix][i])
            if pd.isnull(t_peak1):
                continue
            if peak1_is_first_peak: #similar to condition "i==0" in previous version
                idx2=i+1
                while df.loc[idx2].isnull().any() or (location!='step_2' and df['RSD(%)'][idx2]>1.5):
                    idx2+=1
                idx3=idx2+1
                while df.loc[idx3].isnull().any() or (location!='step_2' and df['RSD(%)'][idx3]>1.5):
                    idx3+=1
                if not df.loc[i].isnull().any() or (location!='step_2' and df['RSD(%)'][i]>1.5):
                    peak1_is_first_peak=False #Other peaks are no longer the first available one
            else:
                idx2=i-1
                while df.loc[idx2].isnull().any() or (location!='step_2' and df['RSD(%)'][idx2]>1.5):
                    idx2-=1
                idx3=i+1
                peak1_is_last_peak=False # assume that peak 1 is not the last peak
                
                #In case idx3 exceeds the range of df
                #That means peak 1 is the last peak
                if idx3>=df.shape[0]: 
                    peak1_is_last_peak=True
                while df.loc[idx3].isnull().any() or (location!='step_2' and df['RSD(%)'][idx3]>1.5):
                    idx3+=1

                    #When idx3 can exceed the range of index of df, peak 1 is
                    #the last peak
                    if idx3>=df.shape[0]:
                        peak1_is_last_peak=True
                        break
                
                #This part is equavalent to the procession for the last peak,
                #and it can also prevent the error when the last peak is not
                #labelled as the last index
                if peak1_is_last_peak:
                    idx3=idx2-1
                    while df.loc[idx3].isnull().any() or (location!='step_2' and df['RSD(%)'][idx3]>1.5):
                        idx3-=1

            t_peak2 = float(df[str(j)+time_suffix][idx2])
            t_peak3 = float(df[str(j)+time_suffix][idx3])
            t_peak1_average_of_all_samples = float(df['Average_MT'][i])
            t_peak2_average_of_all_samples = float(df['Average_MT'][idx2])
            t_peak3_average_of_all_samples = float(df['Average_MT'][idx3])
            EORMT1 = abs((t_peak1/t_peak2)/(t_peak1_average_of_all_samples/t_peak2_average_of_all_samples)-1)
            EORMT2 = abs((t_peak1/t_peak3)/(t_peak1_average_of_all_samples/t_peak3_average_of_all_samples)-1)
            if EORMT1>=allowed_EORMT and EORMT2>=allowed_EORMT:
                if 'Transition' in df.columns and 'Label' not in df.columns:
                    print('Transition {} in sample {} is abnormal, EORMT is {:.2%}>2.5% to the left peak (in transition {}) and {:.2%}>2.5% to the right peak (in transition {}).'.format(
                        df.loc[i,'Transition'],j,EORMT1,df.loc[idx2,'Transition'],EORMT2,df.loc[idx3,'Transition']))
                elif 'Transition' in df.columns and 'Label' in df.columns:
                    print('Peak {}{} in sample {} is abnormal, EORMT is {:.2%}>2.5% to the left peak ({}{}) and {:.2%}>2.5% to the right peak ({}{}).'.format(
                        df.loc[i,'Transition'],df.loc[i,'Label'],j,EORMT1,df.loc[idx2,'Transition'],df.loc[idx2,'Label'],EORMT2,df.loc[idx3,'Transition'],df.loc[idx3,'Label']))
                if location=='step_2':
                    df.loc[i,'remove']=True
                else:
                    if t_peak1<t_peak1_average_of_all_samples:
                        df.loc[i,'earlyList'].append(j)
                    else:
                        df.loc[i,'lateList'].append(j)

    if location=='step_2':    
        df=df[df['remove']==False]
        df=df.drop('remove',axis='columns')
    else:
        idx=0
        df_preupdate=df.sort_values(by=['Transition','Label'])
        min_transition=min(df_preupdate['Transition'])
        max_transition=max(df_preupdate['Transition'])

        #Edit transition No. i
        for i in range(min_transition,max_transition+1):
            print('Processing peaks in Transition '+str(i)+'.')
            peaks_in_one_transition=df_preupdate[df_preupdate['Transition']==i]
            peaks_in_one_transition=peaks_in_one_transition.reset_index(drop=True)
            num_of_peaks_in_one_transition=peaks_in_one_transition.shape[0]
            if num_of_peaks_in_one_transition==0:
                continue
            idx=0
            update_label=0
            peaks_in_one_transition_update_not_exist=True

            for idx in range(0,num_of_peaks_in_one_transition):
                analyzed_peak=peaks_in_one_transition.iloc[idx]

                if get_num_of_peaks_in_a_row(analyzed_peak)/num_of_samples<0.8:
                    can_recombine=True
                else:
                    can_recombine=False

                # Initialize variable
                peaks_earlyList=pd.DataFrame({'Transition':[i],'Label':np.nan})#Label temporarily unavailable
                peaks_normalList=pd.DataFrame({'Transition':[i],'Label':np.nan})#Label temporarily unavailable
                peaks_lateList=pd.DataFrame({'Transition':[i],'Label':np.nan})#Label temporarily unavailable
                analyzed_peak_update_not_exist=True
                normalListNotNull=False

                for j in range(1,num_of_samples+1):
                    peaks_earlyList[str(j)+'_time']=np.nan
                    peaks_earlyList[str(j)+'_area']=np.nan
                    peaks_normalList[str(j)+'_time']=np.nan
                    peaks_normalList[str(j)+'_area']=np.nan
                    peaks_lateList[str(j)+'_time']=np.nan
                    peaks_lateList[str(j)+'_area']=np.nan
                    if time_suffix!='_time':
                        peaks_earlyList[str(j)+time_suffix]=np.nan
                        peaks_normalList[str(j)+time_suffix]=np.nan
                        peaks_lateList[str(j)+time_suffix]=np.nan
                    if j in analyzed_peak['earlyList']:
                        peaks_earlyList[str(j)+'_time']=analyzed_peak[str(j)+'_time']
                        peaks_earlyList[str(j)+'_area']=analyzed_peak[str(j)+'_area']
                        if time_suffix!='_time':
                            peaks_earlyList[str(j)+time_suffix]=analyzed_peak[str(j)+time_suffix]
                    elif j in analyzed_peak['lateList']:
                        peaks_lateList[str(j)+'_time']=analyzed_peak[str(j)+'_time']
                        peaks_lateList[str(j)+'_area']=analyzed_peak[str(j)+'_area']
                        if time_suffix!='_time':
                            peaks_lateList[str(j)+time_suffix]=analyzed_peak[str(j)+time_suffix]
                    else:
                        if pd.notnull(analyzed_peak[str(j)+'_time']):
                            normalListNotNull=True
                        peaks_normalList[str(j)+'_time']=analyzed_peak[str(j)+'_time']
                        peaks_normalList[str(j)+'_area']=analyzed_peak[str(j)+'_area']
                        if time_suffix!='_time':
                            peaks_normalList[str(j)+time_suffix]=analyzed_peak[str(j)+time_suffix]
   
                #analyzed_peak will not be empty
                if len(analyzed_peak['earlyList'])!=0:
                    update_label+=1
                    peaks_earlyList['Label']=chr(update_label+64)
                    analyzed_peak_update=peaks_earlyList
                    analyzed_peak_update_not_exist=False
                if normalListNotNull:
                    update_label+=1
                    peaks_normalList['Label']=chr(update_label+64)
                    if analyzed_peak_update_not_exist:
                        analyzed_peak_update=peaks_normalList
                        analyzed_peak_update_not_exist=False
                    else:
                        analyzed_peak_update=pd.concat([analyzed_peak_update,peaks_normalList])
                if len(analyzed_peak['lateList'])!=0:
                    update_label+=1
                    peaks_lateList['Label']=chr(update_label+64)
                    if analyzed_peak_update_not_exist:
                        analyzed_peak_update=peaks_lateList
                    else:
                        analyzed_peak_update=pd.concat([analyzed_peak_update,peaks_lateList])
                
                analyzed_peak_update['RSD_recombine']=can_recombine
                
                if peaks_in_one_transition_update_not_exist:
                    peaks_in_one_transition_update=analyzed_peak_update
                    peaks_in_one_transition_update_not_exist=False
                else:
                    peaks_in_one_transition_update=pd.concat([peaks_in_one_transition_update,analyzed_peak_update])

            if i==min_transition:
                df_without_RSD_correction=peaks_in_one_transition_update
            else:
                df_without_RSD_correction=pd.concat([df_without_RSD_correction,peaks_in_one_transition_update])

            '''Modification Step: Modify previous modification: if two set of peaks are consecutive 
            in one transition and both of these peaks do not appear in a single sample 
            simutaneously, a RSD < 2.5 % criterion will be adopted to recombine the result'''
            j=0
            num_of_lines=peaks_in_one_transition_update.shape[0]
            while j<num_of_lines-1:
                metabolite_checking=with_avgMT_and_RSD(peaks_in_one_transition_update.iloc[j])
                if j!=0:
                    metabolite_prev=with_avgMT_and_RSD(peaks_in_one_transition_update.iloc[j-1])
                    mergeable_prev=metabolite_prev['RSD_recombine'] and metabolite_checking['RSD_recombine']
                    '''mergeable_prev=(get_num_of_peaks_in_a_row(metabolite_prev)/num_of_samples<0.8) and \
                        (get_num_of_peaks_in_a_row(metabolite_checking)/num_of_samples<0.8)'''
                else:
                    mergeable_prev=False
                if j!=num_of_lines:                    
                    metabolite_post=with_avgMT_and_RSD(peaks_in_one_transition_update.iloc[j+1])
                    mergeable_post=metabolite_post['RSD_recombine'] and metabolite_checking['RSD_recombine']
                    '''mergeable_post=(get_num_of_peaks_in_a_row(metabolite_post)/num_of_samples<0.8) and \
                        (get_num_of_peaks_in_a_row(metabolite_checking)/num_of_samples<0.8)'''
                else:
                    mergeable_post=False

                for label_use_no in range(1,num_of_samples+1):
                    label=str(label_use_no)+time_suffix
                    if mergeable_prev and pd.notnull(metabolite_prev[label]) and \
                        pd.notnull(metabolite_checking[label]):
                        mergeable_prev=False
                    if mergeable_post and pd.notnull(metabolite_post[label]) and \
                        pd.notnull(metabolite_checking[label]):
                        mergeable_post=False

                if mergeable_prev and mergeable_post:
                    if metabolite_post['Average_MT']-metabolite_checking['Average_MT']>\
                        metabolite_checking['Average_MT']-metabolite_prev['Average_MT']:
                        mergeable_post=False
                    else:
                        mergeable_prev=False

                #Trial of mergeable sets of peaks
                if mergeable_prev:
                    trial_merged_peaks=with_avgMT_and_RSD(metabolite_prev.add(metabolite_checking,fill_value=0))
                    if trial_merged_peaks['RSD(%)']<2.5:
                        peaks_in_one_transition_update['Label']=peaks_in_one_transition_update['Label'].map(lambda l:chr(ord(l)-1) if ord(l)>=j+65 else l)
                        j-=1

                if mergeable_post:
                    trial_merged_peaks=with_avgMT_and_RSD(metabolite_post.add(metabolite_checking,fill_value=0))
                    if trial_merged_peaks['RSD(%)']<2.5:
                        peaks_in_one_transition_update['Label']=peaks_in_one_transition_update['Label'].map(lambda l:chr(ord(l)-1) if ord(l)>j+65 else l)
                
                if mergeable_prev or mergeable_post:
                        peaks_in_one_transition_update=peaks_in_one_transition_update.groupby('Label',sort=False).max()
                        peaks_in_one_transition_update=peaks_in_one_transition_update.reset_index()
                        peaks_in_one_transition_update=peaks_in_one_transition_update.set_index(['Transition','Label'])
                        peaks_in_one_transition_update=peaks_in_one_transition_update.reset_index()
                        num_of_lines-=1
                        
                j+=1

            if i==min_transition:
                df=peaks_in_one_transition_update
            else:
                df=pd.concat([df,peaks_in_one_transition_update])

    if axes_name!=None: #The most common example: 'Transition' as index
        df=df.set_index(axes_name)
    elif axes_names!=[None]: #The most common example: ('Transition','Label') as index
        df=df.set_index(axes_names)
    else: #No previous index
        df=df.reset_index(drop=True)
        df.index=df.index+1

    if location=='step_2':
        return df
    else:
        if axes_name!=None: #The most common example: 'Transition' as index
            df_without_RSD_correction=df_without_RSD_correction.set_index(axes_name)
        elif axes_names!=[None]: #The most common example: ('Transition','Label') as index
            df_without_RSD_correction=df_without_RSD_correction.set_index(axes_names)
        else: #No previous index
            df_without_RSD_correction=df_without_RSD_correction.reset_index(drop=True)
            df_without_RSD_correction.index=df_without_RSD_correction.index+1
        
        df_without_RSD_correction=df_without_RSD_correction.drop('RSD_recombine',axis='columns')
        df=df.drop('RSD_recombine',axis='columns')    
        return df_without_RSD_correction,df

In [9]:
# Function 2: Suggest the potential migration time markers for phase 1 and phase 2 
# based on three conditions: 1. only one peak is found in that transition(Q1→Q3);
# 2. this analyte can be found in all samples; 3. this analyte should only be found
# either in phase 1 or phase 2.

# If time_p_chnage is set as a double value, the removal part will be run
# If time_p_chnage is set as False, the removal part will not be run

def F2_find_markers(dfs,time_p_change):
    # Get the number of transitions from a sample set
    num_of_transitions=get_max_transition_num(dfs)
    one_peak=pd.DataFrame({'contains_one_peak':[True]*(num_of_transitions+1)},
                          index=range(0,(num_of_transitions+1)))

    # Find the one-peak transition
    for i in range(1,len(dfs)+1):
        num_is_one=dfs[i].groupby(['Transition'])['Transition'].count()==1
        for j in range(0,num_of_transitions+1):
            if j not in num_is_one.index or not num_is_one[j]:
                one_peak['contains_one_peak'][j]=False
    selected=one_peak.loc[one_peak['contains_one_peak']].index
    df_time_area=dfs[1].set_index('Transition').loc[selected]
    for i in range(2,len(dfs)+1):
        right=dfs[i].set_index('Transition').loc[selected]
        df_time_area=df_time_area.join(right)

    # Review all analytes migration times and peak areas
    print('All {} one-peak transitions were selected.'.format(df_time_area.shape[0]))
    print('')
    df_time=df_time_area
    for i in range(1,len(dfs)+1):
        df_time=df_time.drop(str(i)+'_area',axis=1)
    df_time=with_avgMT_and_RSD(df_time)
    df_time.insert(0,'Transition',df_time.index)
    df_time=df_time.sort_values(by='Average_MT').reset_index(drop=True) #Perhaps can be deleted

    # If time_p_chnage is set as a double value, the following part will be run
    # If time_p_chnage is set as False, the following part will not be run
    if time_p_change:
        # Remove the intermediate phase peaks
        print('The following transitions will be removed, because analytes in these transistions were detected in both phase 1 and phase 2.')
        for i in range(0,len(df_time.index)):
            times = df_time.loc[i,:]
            times = times.drop(['Transition','Average_MT','RSD(%)'])
            times_max = times.max(axis=0)
            times_min = times.min(axis=0)
            avg = float(df_time['Average_MT'][i])
            if times_max > time_p_change and times_min < time_p_change:
                print('The transition {} is removed.'.format(int(df_time.loc[i, ['Transition']])))
                df_time = df_time.drop([i])
        df_time=df_time.reset_index(drop=True)
        df_time.index=df_time.index+1
        print('')

        # Only keep the one-analyte transistion by checking the migration order of each peak with its adjacent peaks.
        df_phase1 = df_time[df_time['Average_MT'] < time_p_change].reset_index(drop=True).copy()
        df_phase2 = df_time[df_time['Average_MT'] >= time_p_change].reset_index(drop=True).copy()
        print('The relative position for each peak will be checked according to its two adjacent peaks.')
        print('Start to check phase 1 analytes:')
        df_phase1=check_and_correct(df_phase1,0.025,'step_2')
        print('Phase 1 peaks have been checked.')

        print('Start to check phase 2 analytes:')
        df_phase2=check_and_correct(df_phase2,0.025,'step_2')
        print('Phase 2 peaks have been checked.')
        print('The above transitions were removed because they may be assigned to more than 1 analyte.')

        df_time=pd.concat([df_phase1,df_phase2])
    else:
        print('No peaks are checked and removed, for variable "check_and_correct" is set as False.')
    print('')
    df_time=df_time.reset_index(drop=True)
    df_time.index=df_time.index+1
    print('Function 2 is completed.')
    print('')

    return df_time

In [10]:
# Using Function 2
# Apply Function 2 to find potencial migration time markers
pd.set_option('precision', 2)
time_p_change = 20
potential_markers = F2_find_markers(dfs, time_p_change)
print('Migration time markers for phase 1 and phase 2 may be selected from the following table:')
print('')
print(potential_markers)

All 32 one-peak transitions were selected.

The following transitions will be removed, because analytes in these transistions were detected in both phase 1 and phase 2.
The transition 147 is removed.
The transition 230 is removed.
The transition 262 is removed.
The transition 260 is removed.
The transition 258 is removed.

The relative position for each peak will be checked according to its two adjacent peaks.
Start to check phase 1 analytes:
Transition 125 in sample 1 is abnormal, EORMT is 27.36%>2.5% to the left peak (in transition 27) and 26.14%>2.5% to the right peak (in transition 14).
Transition 14 in sample 1 is abnormal, EORMT is 20.72%>2.5% to the left peak (in transition 125) and 5.48%>2.5% to the right peak (in transition 60).
Transition 125 in sample 3 is abnormal, EORMT is 6.43%>2.5% to the left peak (in transition 27) and 4.43%>2.5% to the right peak (in transition 14).
Transition 125 in sample 4 is abnormal, EORMT is 4.97%>2.5% to the left peak (in transition 27) and 4.23%>2.5% to the right peak (in transition 14).
Transition 125 in sample 5 is abnormal, EORMT is 3.80%>2.5% to the left peak (in transition 27) and 4.70%>2.5% to the right peak (in transition 14).
Transition 125 in sample 8 is abnormal, EORMT is 13.53%>2.5% to the left peak (in transition 27) and 13.11%>2.5% to the right peak (in transition 14).
Transition 14 in sample 8 is abnormal, EORMT is 11.59%>2.5% to the left peak (in transition 125) and 2.83%>2.5% to the right peak (in transition 60).
Transition 125 in sample 9 is abnormal, EORMT is 5.81%>2.5% to the left peak (in transition 27) and 4.04%>2.5% to the right peak (in transition 14).
Transition 125 in sample 11 is abnormal, EORMT is 2.70%>2.5% to the left peak (in transition 27) and 3.68%>2.5% to the right peak (in transition 14).
Transition 14 in sample 13 is abnormal, EORMT is 5.14%>2.5% to the left peak (in transition 125) and 2.61%>2.5% to the right peak (in transition 60).
Transition 125 in sample 14 is abnormal, EORMT is 14.69%>2.5% to the left peak (in transition 27) and 14.07%>2.5% to the right peak (in transition 14).
Transition 14 in sample 14 is abnormal, EORMT is 12.33%>2.5% to the left peak (in transition 125) and 3.08%>2.5% to the right peak (in transition 60).
Transition 125 in sample 15 is abnormal, EORMT is 2.53%>2.5% to the left peak (in transition 27) and 5.30%>2.5% to the right peak (in transition 14).
Transition 125 in sample 16 is abnormal, EORMT is 6.71%>2.5% to the left peak (in transition 27) and 4.13%>2.5% to the right peak (in transition 14).
Transition 125 in sample 17 is abnormal, EORMT is 6.16%>2.5% to the left peak (in transition 27) and 4.72%>2.5% to the right peak (in transition 14).
Transition 14 in sample 17 is abnormal, EORMT is 4.96%>2.5% to the left peak (in transition 125) and 2.89%>2.5% to the right peak (in transition 60).
Transition 125 in sample 22 is abnormal, EORMT is 14.47%>2.5% to the left peak (in transition 27) and 14.96%>2.5% to the right peak (in transition 14).
Transition 125 in sample 24 is abnormal, EORMT is 5.48%>2.5% to the left peak (in transition 27) and 3.70%>2.5% to the right peak (in transition 14).
Transition 14 in sample 25 is abnormal, EORMT is 3.95%>2.5% to the left peak (in transition 125) and 3.56%>2.5% to the right peak (in transition 60).
Transition 14 in sample 26 is abnormal, EORMT is 4.43%>2.5% to the left peak (in transition 125) and 2.95%>2.5% to the right peak (in transition 60).
Transition 125 in sample 28 is abnormal, EORMT is 5.27%>2.5% to the left peak (in transition 27) and 4.67%>2.5% to the right peak (in transition 14).
Transition 14 in sample 28 is abnormal, EORMT is 4.46%>2.5% to the left peak (in transition 125) and 3.56%>2.5% to the right peak (in transition 60).
Phase 1 peaks have been checked.
Start to check phase 2 analytes:
Phase 2 peaks have been checked.
The above transitions were removed because they may be assigned to more than 1 analyte.

Function 2 is completed.

Migration time markers for phase 1 and phase 2 may be selected from the following table:

    index  Transition  1_time  2_time  ...  31_time  32_time  Average_MT  RSD(%)
1       0         253    4.83    5.30  ...     5.14     5.31        5.05    5.04
2       1          37    5.49    5.92  ...     5.80     5.89        5.68    5.10
3       2          38    5.61    6.27  ...     6.05     6.20        5.96    5.34
4       3          27    6.67    7.57  ...     7.26     7.51        7.17    5.62
5       6          60   10.63   13.34  ...    12.25    12.19       11.94    8.18
6       7           3   10.63   13.34  ...    12.25    12.22       11.95    8.17
7       8          36   10.69   13.50  ...    12.34    12.28       12.05    8.17
8       9          39   10.72   13.72  ...    12.66    12.66       12.29    8.49
9      10         163   10.88   13.87  ...    12.75    12.94       12.47    8.47
10     11         161   10.88   13.87  ...    12.84    12.94       12.48    8.55
11     12           0   10.88   13.90  ...    12.81    12.94       12.48    8.54
12     13          12   10.91   13.93  ...    12.91    12.88       12.49    8.49
13     14         225   11.00   14.21  ...    13.06    13.06       12.70    8.69
14     15         185   11.19   14.37  ...    13.22    13.19       12.85    8.77
15     16         162   11.22   14.43  ...    13.19    13.22       12.87    8.75
16     17         198   11.22   14.46  ...    13.22    13.28       12.91    8.80
17     18          62   11.29   14.46  ...    13.31    13.31       12.94    8.76
18     19          24   12.03   15.80  ...    14.12    14.09       13.79    9.30
19      0         210   20.95   25.97  ...    23.88    23.79       23.44    7.21
20      1         182   21.35   26.65  ...    24.13    24.10       23.91    7.39
21      2         168   21.82   27.37  ...    24.75    24.63       24.51    7.56
22      3          81   22.10   27.90  ...    24.69    24.51       24.68    7.73
23      4         132   22.38   28.37  ...    25.47    25.31       25.26    7.82
24      5          28   22.38   28.37  ...    25.53    25.38       25.27    7.83
25      6          98   23.66   30.64  ...    27.34    27.15       27.03    8.40

[25 rows x 36 columns]

In [11]:
potential_markers
# Based on the following results, we firstly selected the analytes in transitions 38 (1-methylnicotinamide) and 24 (taurine)
# as the phase 1 markers, and the analytes in transitions 182 (N-acetyltryptophan) and 98 (hippuric acid) as the phase 2 markers.

    index  Transition  1_time  2_time  ...  31_time  32_time  Average_MT  RSD(%)
1       0         253    4.83    5.30  ...     5.14     5.31        5.05    5.04
2       1          37    5.49    5.92  ...     5.80     5.89        5.68    5.10
3       2          38    5.61    6.27  ...     6.05     6.20        5.96    5.34
4       3          27    6.67    7.57  ...     7.26     7.51        7.17    5.62
5       6          60   10.63   13.34  ...    12.25    12.19       11.94    8.18
6       7           3   10.63   13.34  ...    12.25    12.22       11.95    8.17
7       8          36   10.69   13.50  ...    12.34    12.28       12.05    8.17
8       9          39   10.72   13.72  ...    12.66    12.66       12.29    8.49
9      10         163   10.88   13.87  ...    12.75    12.94       12.47    8.47
10     11         161   10.88   13.87  ...    12.84    12.94       12.48    8.55
11     12           0   10.88   13.90  ...    12.81    12.94       12.48    8.54
12     13          12   10.91   13.93  ...    12.91    12.88       12.49    8.49
13     14         225   11.00   14.21  ...    13.06    13.06       12.70    8.69
14     15         185   11.19   14.37  ...    13.22    13.19       12.85    8.77
15     16         162   11.22   14.43  ...    13.19    13.22       12.87    8.75
16     17         198   11.22   14.46  ...    13.22    13.28       12.91    8.80
17     18          62   11.29   14.46  ...    13.31    13.31       12.94    8.76
18     19          24   12.03   15.80  ...    14.12    14.09       13.79    9.30
19      0         210   20.95   25.97  ...    23.88    23.79       23.44    7.21
20      1         182   21.35   26.65  ...    24.13    24.10       23.91    7.39
21      2         168   21.82   27.37  ...    24.75    24.63       24.51    7.56
22      3          81   22.10   27.90  ...    24.69    24.51       24.68    7.73
23      4         132   22.38   28.37  ...    25.47    25.31       25.26    7.82
24      5          28   22.38   28.37  ...    25.53    25.38       25.27    7.83
25      6          98   23.66   30.64  ...    27.34    27.15       27.03    8.40

[25 rows x 36 columns]

In [12]:
# Function 3: Calculate γ according to the selected markers
def get_gamma(dfs, sample_num, df_std, m1_transition,m2_transition):
    df_std_temp = df_std.set_index('Transition')
    # Using the average MT as the standard MT
    tm1_std = df_std_temp.loc[m1_transition,'Average_MT'] 
    tm2_std = df_std_temp.loc[m2_transition,'Average_MT']
    df_temp = dfs[sample_num].set_index('Transition')
    tm1 = df_temp.loc[m1_transition,str(sample_num)+'_time']
    tm2 = df_temp.loc[m2_transition,str(sample_num)+'_time']
    gamma = ((1/tm1)-(1/tm2))/((1/tm1_std)-(1/tm2_std))
    return gamma

In [13]:
# Using Function 3
sample_num = 19
m1_transition = 38
m2_transition = 24
m3_transition = 210
m4_transition = 98
gamma_phase1 = get_gamma(dfs, sample_num, potential_markers, m1_transition, m2_transition)
gamma_phase2 = get_gamma(dfs, sample_num, potential_markers, m3_transition, m4_transition)
print('For sample '+str(sample_num)+', the γ1 is '+str(gamma_phase1)+' and the γ2 is '+str(gamma_phase2))

For sample 19, the γ1 is 0.9525242869121221 and the γ2 is 0.991554637998258

In [14]:
# Function 4: Correct the migration times by using 4 markers
# If migration times cannot be corrected by these markers due to gamma equals 0, return -1

# If time_p_chnage is set as a double value, two gamma method will be adopted
# If time_p_chnage is set as False, three gamma method will be adopted
def correcting_by4markers(dfs_input,df_std,m1_transition,m2_transition,m3_transition,m4_transition,time_p_change):

    #To avoid modifying input parameter
    dfs=dfs_input.copy()
    
    df_std_temp = df_std.set_index('Transition')
    tm1_std = df_std_temp.loc[m1_transition,'Average_MT']
    tm2_std = df_std_temp.loc[m2_transition,'Average_MT']
    tm3_std = df_std_temp.loc[m3_transition,'Average_MT']
    for i in range(1,len(dfs)+1):
        gamma1 = get_gamma(dfs, i, df_std, m1_transition, m2_transition)
        gamma2 = get_gamma(dfs, i, df_std, m3_transition, m4_transition)
        if gamma1==0:
            print('Migration times cannot be corrected by m1_transition='+str(m1_transition)+\
                ' and m2_transition='+str(m2_transition)+', because their migration '+\
                'times in sample '+str(i)+' are identical.')
            return -1
        if gamma2==0:
            print('Migration times cannot be corrected by m3_transition='+str(m3_transition)+\
                  ' and m4_transition='+str(m4_transition)+', because their migration '+\
                  'times in sample '+str(i)+' are identical.')
            return -1
        if not time_p_change:
            gamma_intermediate_phase = get_gamma(dfs, i, df_std, m2_transition, m3_transition)
            if gamma_intermediate_phase==0:
                print('Migration times cannot be corrected by m2_transition='+str(m2_transition)+\
                    ' and m3_transition='+str(m3_transition)+', because their migration '+\
                    'times in sample '+str(i)+' are identical.')
                return -1
        df_temp = dfs[i].set_index('Transition')
        tm1 = df_temp.loc[m1_transition,str(i)+'_time']
        tm2 = df_temp.loc[m2_transition,str(i)+'_time']
        tm3 = df_temp.loc[m3_transition,str(i)+'_time']
        dfs[i][str(i)+'_time_4markers']= None
        analyte_num = dfs[i].shape[0]
        for j in range(0,analyte_num):
            t_origin = dfs[i].loc[j,str(i)+'_time']
            if time_p_change:
                if t_origin <= time_p_change:
                    t_4marker_p = 1/((1/tm1_std)-(1/gamma1)*((1/tm1)-(1/t_origin)))
                else:
                    t_4marker_p = 1/((1/tm3_std)-(1/gamma2)*((1/tm3)-(1/t_origin)))
            else:
                if t_origin <= tm2:
                    t_4marker_p = 1/((1/tm1_std)-(1/gamma1)*((1/tm1)-(1/t_origin)))
                elif t_origin <= tm3:
                    t_4marker_p = 1/((1/tm2_std)-(1/gamma_intermediate_phase)*((1/tm2)-(1/t_origin)))
                else:
                    t_4marker_p = 1/((1/tm3_std)-(1/gamma2)*((1/tm3)-(1/t_origin)))
            dfs[i].loc[j,str(i)+'_time_4markers'] = t_4marker_p
    return dfs

In [15]:
# Using Function 4
# Apply Function 4 to create a new column with 4-marker corrected migration times
m1_transition = 38
m2_transition = 24
m3_transition = 182
m4_transition = 98
time_p_change = 20
corrected_dfs=correcting_by4markers(dfs, potential_markers,m1_transition, m2_transition,m3_transition, m4_transition, time_p_change)

In [16]:
pd.set_option('precision', 6)
corrected_dfs[32].head(38)

    Transition  32_time     32_area 32_time_4markers
0            0    12.94   6642411.0          12.6289
1            1    13.12   2675259.0          12.8101
2            1    14.31    104233.0          14.0117
3            2     6.02     44876.0          5.77998
4            3    12.22    290774.0          11.9058
5            5     7.61    150544.0          7.33392
6            6    13.12     47704.0          12.8101
7            8     9.57     30822.0          9.26554
8           10    12.56     86985.0           12.247
9           11    12.94    140276.0          12.6289
10          12    12.88  30245364.0          12.5686
11          13    12.84    244068.0          12.5283
12          13    20.92     42080.0          20.6826
13          14     8.88    988073.0          8.58349
14          15    13.12    537786.0          12.8101
15          16    13.16     81345.0          12.8504
16          17    28.03     34595.0          27.9389
17          17    12.66     15902.0          12.3474
18          18    13.22    289318.0          12.9108
19          18    11.91     49571.0          11.5952
20          19    13.19    117770.0          12.8806
21          20     7.64     13610.0          7.36335
22          20     6.20     10990.0          5.95531
23          22    13.12     46801.0          12.8101
24          23     9.70   1775000.0          9.39429
25          24    14.09   6757135.0          13.7891
26          25     7.01    303768.0          6.74616
27          25    14.06    154339.0          13.7587
28          26     7.67     97580.0          7.39278
29          26    12.38     50610.0          12.0663
30          27     7.51     84153.0          7.23584
31          28    25.38    724425.0          25.2205
32          29    13.28    123341.0          12.9713
33          30    13.09    868866.0          12.7799
34          31     8.73     55186.0          8.43551
35          32    13.16     41170.0          12.8504
36          33    13.28     24289.0          12.9713
37          34     8.85     53310.0          8.55389

In [17]:
#Function 5: Peak alignment
#RSDTolerance: maximum allowed RSD for MT in preliminary alignment step
#concatenateTolerance: maximun allowed range for corrected MT in modification step
#if concatenateTolerance == 0, modification step will not make a difference on the result
def align(corrected_dfs_input,RSDTolerance,concatenateTolerance):

    #To avoid modifying input parameter
    dfs=corrected_dfs_input.copy()
    num = len(dfs)

    if '1_time_6markers' in dfs[1].columns:
        suffix='_time_6markers'
    elif '1_time_4markers' in dfs[1].columns:
        suffix='_time_4markers'
    else:
        print('Time in data has not been corrected')
        return

    for i in range(1,num+1):
        dfs[i]['sample_no']=i;
        if suffix=='_time_6markers':
            dfs[i]=dfs[i].rename(columns={str(i)+'_time':'time',str(i)+'_area':'area',str(i)+'_time_6markers':'time_corrected'})
        elif suffix=='_time_4markers':
            dfs[i]=dfs[i].rename(columns={str(i)+'_time':'time',str(i)+'_area':'area',str(i)+'_time_4markers':'time_corrected'})
    
    num_of_transitions = 0
    for i in range(1,num+1):
        if dfs[i]['Transition'].max()>num_of_transitions:
            num_of_transitions=dfs[i]['Transition'].max()
    transitions=range(0,num_of_transitions+1);
    for i in transitions:
        print("The peaks in transition "+str(i)+" of "+str(num)+" samples have been aligned.")
        # Selected peaks in all samples in single transition
        for no_of_sample,sample in dfs.items():
            peaks_in_one_transition_in_one_sample=sample.loc[sample['Transition']==i]
            if no_of_sample==1 or peaks_in_one_transition.empty:
                peaks_in_one_transition=peaks_in_one_transition_in_one_sample
            else:
                peaks_in_one_transition=pd.concat([peaks_in_one_transition,peaks_in_one_transition_in_one_sample])
        
        # Skip the empty transition
        if peaks_in_one_transition.shape[0]==0:
            continue;

        peaks_in_one_transition=peaks_in_one_transition.sort_values(by='time_corrected')
        peaks_in_one_transition['']=range(0,peaks_in_one_transition.shape[0])
        peaks_in_one_transition=peaks_in_one_transition.set_index('')
        num_of_peaks_in_one_transition=peaks_in_one_transition.shape[0]
        label_of_peak=1
        idx=0
        idx2=0

        # Preliminary alignment step: align the peaks in single transition
        while idx<num_of_peaks_in_one_transition:
            selected_samples=[]
            min_time=peaks_in_one_transition['time_corrected'][idx]
            analyzed_peak=peaks_in_one_transition.iloc[idx]

            # Initialize variable peaks_aligned_as_one_metabolite
            peaks_aligned_as_one_metabolite=pd.DataFrame({'Transition':[i],'Label':[chr(label_of_peak+64)]})
            for j in range(1,num+1):
                peaks_aligned_as_one_metabolite[str(j)+'_time']=np.nan
                peaks_aligned_as_one_metabolite[str(j)+'_area']=np.nan
                peaks_aligned_as_one_metabolite[str(j)+'_time_corrected']=np.nan

            # Select the first few peaks that are not in the same samples (forward-to-backward scheme)
            while analyzed_peak['sample_no'] not in selected_samples:
                selected_samples.append(analyzed_peak['sample_no'])
                idx+=1
                if idx==num_of_peaks_in_one_transition:
                    break
                analyzed_peak=peaks_in_one_transition.iloc[idx]

            # Eliminate peaks to satisfy RSD condition
            while np.std(list(peaks_in_one_transition['time_corrected'][idx2:idx]))/\
            np.mean(list(peaks_in_one_transition['time_corrected'][idx2:idx]))>=RSDTolerance:
                idx-=1

            # Select peaks that can be aligned as one metabolite
            for j in range(idx2,idx):
                analyzed_peak=peaks_in_one_transition.loc[j]
                selected_samples.append(analyzed_peak['sample_no'])
                peaks_aligned_as_one_metabolite[str(analyzed_peak['sample_no'])+'_time']=analyzed_peak['time']
                peaks_aligned_as_one_metabolite[str(analyzed_peak['sample_no'])+'_area']=analyzed_peak['area']
                peaks_aligned_as_one_metabolite[str(analyzed_peak['sample_no'])+'_time_corrected']=analyzed_peak['time_corrected']

            # Prepare to select peaks for another metabolites
            if len(selected_samples)>=1:
                if label_of_peak==1:
                    peaks_aligned_in_one_transition=peaks_aligned_as_one_metabolite
                else:
                    peaks_aligned_in_one_transition=pd.concat([peaks_aligned_in_one_transition,\
                                        peaks_aligned_as_one_metabolite])
                label_of_peak+=1

            idx2=idx

        '''Modification Step: Modify previous alignment: if two set of peaks are aligned as consecutive 
        metabolites in one transition and both of these peaks do not appear in a single sample 
        simutaneously, a loose criterion will be adopted to modify the result'''
        j=0
        lines=peaks_aligned_in_one_transition.shape[0]
        while j<lines-1:
            metabolite_1=peaks_aligned_in_one_transition.iloc[j]
            metabolite_2=peaks_aligned_in_one_transition.iloc[j+1]
            metabolite_1.drop(['Transition','Label'])
            metabolite_2.drop(['Transition','Label'])

            # Examine each corrected time to select the maximum and minimum migration time
            max_time=0
            min_time=2**31
            merge=True;
            for label_use_no in range(1,num+1):
                label=str(label_use_no)+'_time_corrected'
                if pd.notnull(metabolite_1[label]) and pd.notnull(metabolite_2[label]):
                    merge=False;
                    break;
                if pd.notnull(metabolite_1[label]):
                    max_time=max(metabolite_1[label],max_time)
                    min_time=min(metabolite_1[label],min_time)
                elif pd.notnull(metabolite_2[label]):
                    max_time=max(metabolite_2[label],max_time)
                    min_time=min(metabolite_2[label],min_time)
            merge=merge and max_time-min_time<=concatenateTolerance
            if merge:
                peaks_aligned_in_one_transition['Label']=peaks_aligned_in_one_transition['Label'].map(lambda l:chr(ord(l)-1) if ord(l)>j+65 else l)
                peaks_aligned_in_one_transition=peaks_aligned_in_one_transition.groupby('Label',sort=False).max()
                peaks_aligned_in_one_transition=peaks_aligned_in_one_transition.reset_index()
                peaks_aligned_in_one_transition=peaks_aligned_in_one_transition.set_index(['Transition','Label'])
                peaks_aligned_in_one_transition=peaks_aligned_in_one_transition.reset_index()
                lines-=1
            j+=1

        peaks_aligned_in_one_transition=peaks_aligned_in_one_transition.reset_index()

        # Modification step: due to weakness of "forward-to-backward" scheme, the last peak in a metabolite will be tried to align in the next metabolite
        for j in range(0,peaks_aligned_in_one_transition.shape[0]-1):
            while True:
                peaks_aligned_in_one_transition=with_avgMT_and_RSD(peaks_aligned_in_one_transition)
                max_MT_in_one_metabolite = 0
                min_MT_in_next_metabolite = 0
                count_this = 0
                count_next = 0
                for k in range(1,num+1):
                    if not pd.isnull(peaks_aligned_in_one_transition.loc[j,str(k)+'_time_corrected']):
                        count_this = count_this + 1
                    if peaks_aligned_in_one_transition.loc[j,str(k)+'_time_corrected']>max_MT_in_one_metabolite:
                        max_MT_in_one_metabolite=peaks_aligned_in_one_transition.loc[j,str(k)+'_time_corrected']
                        peak_with_max_MT=k

                min_MT_in_next_metabolite=2**31
                for k in range(1,num+1):
                    if not pd.isnull(peaks_aligned_in_one_transition.loc[j+1,str(k)+'_time_corrected']):
                        count_next = count_next + 1
                    if peaks_aligned_in_one_transition.loc[j+1,str(k)+'_time_corrected']<min_MT_in_next_metabolite:
                        min_MT_in_next_metabolite=peaks_aligned_in_one_transition.loc[j+1,str(k)+'_time_corrected']

                #parameter in 'if' can be optimized
                if pd.isnull(peaks_aligned_in_one_transition.loc[j+1,str(peak_with_max_MT)+'_time_corrected']) and min_MT_in_next_metabolite-max_MT_in_one_metabolite < 0.04 * (peaks_aligned_in_one_transition.loc[j+1,'Average_MT'] - peaks_aligned_in_one_transition.loc[j,'Average_MT']) and count_this < count_next:#min_MT_in_next_metabolite-max_MT_in_one_metabolite < 0.01*peaks_aligned_in_one_transition.loc[j,'Average_MT']:
                    peaks_aligned_in_one_transition.loc[j+1,str(peak_with_max_MT)+'_time']=peaks_aligned_in_one_transition.loc[j,str(peak_with_max_MT)+'_time']
                    peaks_aligned_in_one_transition.loc[j+1,str(peak_with_max_MT)+'_area']=peaks_aligned_in_one_transition.loc[j,str(peak_with_max_MT)+'_area']
                    peaks_aligned_in_one_transition.loc[j+1,str(peak_with_max_MT)+'_time_corrected']=peaks_aligned_in_one_transition.loc[j,str(peak_with_max_MT)+'_time_corrected']
                    peaks_aligned_in_one_transition.loc[j,str(peak_with_max_MT)+'_time']=np.nan
                    peaks_aligned_in_one_transition.loc[j,str(peak_with_max_MT)+'_area']=np.nan
                    peaks_aligned_in_one_transition.loc[j,str(peak_with_max_MT)+'_time_corrected']=np.nan
                else:
                    break

        if i==transitions[0]:
            aligned_dfs=peaks_aligned_in_one_transition
        else:
            aligned_dfs=pd.concat([aligned_dfs,peaks_aligned_in_one_transition])
    aligned_dfs=aligned_dfs.set_index(['Transition','Label'])
    for i in range(1,num+1):
        dfs[i]['sample_no']=i;
        if suffix=='_time_6markers':
            aligned_dfs=aligned_dfs.rename(columns={str(i)+'_time_corrected':str(i)+'_time_6markers'})
        elif suffix=='_time_4markers':
            aligned_dfs=aligned_dfs.rename(columns={str(i)+'_time_corrected':str(i)+'_time_4markers'})
    print("Function 5 is completed.")

    aligned_dfs = aligned_dfs.drop(labels=['Average_MT','RSD(%)'],axis='columns')
    return aligned_dfs

In [18]:
# Using Function 5
aligned_dfs=align(dfs,0.04,3)

The peaks in transition 0 of 32 samples have been aligned.
The peaks in transition 1 of 32 samples have been aligned.
The peaks in transition 2 of 32 samples have been aligned.
The peaks in transition 3 of 32 samples have been aligned.
The peaks in transition 4 of 32 samples have been aligned.
The peaks in transition 5 of 32 samples have been aligned.
The peaks in transition 6 of 32 samples have been aligned.
The peaks in transition 7 of 32 samples have been aligned.
The peaks in transition 8 of 32 samples have been aligned.
The peaks in transition 9 of 32 samples have been aligned.
The peaks in transition 10 of 32 samples have been aligned.
The peaks in transition 11 of 32 samples have been aligned.
The peaks in transition 12 of 32 samples have been aligned.
The peaks in transition 13 of 32 samples have been aligned.
The peaks in transition 14 of 32 samples have been aligned.
The peaks in transition 15 of 32 samples have been aligned.
The peaks in transition 16 of 32 samples have been aligned.
The peaks in transition 17 of 32 samples have been aligned.
The peaks in transition 18 of 32 samples have been aligned.
The peaks in transition 19 of 32 samples have been aligned.
The peaks in transition 20 of 32 samples have been aligned.
The peaks in transition 21 of 32 samples have been aligned.
The peaks in transition 22 of 32 samples have been aligned.
The peaks in transition 23 of 32 samples have been aligned.
The peaks in transition 24 of 32 samples have been aligned.
The peaks in transition 25 of 32 samples have been aligned.
The peaks in transition 26 of 32 samples have been aligned.
The peaks in transition 27 of 32 samples have been aligned.
The peaks in transition 28 of 32 samples have been aligned.
The peaks in transition 29 of 32 samples have been aligned.
The peaks in transition 30 of 32 samples have been aligned.
The peaks in transition 31 of 32 samples have been aligned.
The peaks in transition 32 of 32 samples have been aligned.
The peaks in transition 33 of 32 samples have been aligned.
The peaks in transition 34 of 32 samples have been aligned.
The peaks in transition 35 of 32 samples have been aligned.
The peaks in transition 36 of 32 samples have been aligned.
The peaks in transition 37 of 32 samples have been aligned.
The peaks in transition 38 of 32 samples have been aligned.
The peaks in transition 39 of 32 samples have been aligned.
The peaks in transition 40 of 32 samples have been aligned.
The peaks in transition 41 of 32 samples have been aligned.
The peaks in transition 42 of 32 samples have been aligned.
The peaks in transition 43 of 32 samples have been aligned.
The peaks in transition 44 of 32 samples have been aligned.
The peaks in transition 45 of 32 samples have been aligned.
The peaks in transition 46 of 32 samples have been aligned.
The peaks in transition 47 of 32 samples have been aligned.
The peaks in transition 48 of 32 samples have been aligned.
The peaks in transition 49 of 32 samples have been aligned.
The peaks in transition 50 of 32 samples have been aligned.
The peaks in transition 51 of 32 samples have been aligned.
The peaks in transition 52 of 32 samples have been aligned.
The peaks in transition 53 of 32 samples have been aligned.
The peaks in transition 54 of 32 samples have been aligned.
The peaks in transition 55 of 32 samples have been aligned.
The peaks in transition 56 of 32 samples have been aligned.
The peaks in transition 57 of 32 samples have been aligned.
The peaks in transition 58 of 32 samples have been aligned.
The peaks in transition 59 of 32 samples have been aligned.
The peaks in transition 60 of 32 samples have been aligned.
The peaks in transition 61 of 32 samples have been aligned.
The peaks in transition 62 of 32 samples have been aligned.
The peaks in transition 63 of 32 samples have been aligned.
The peaks in transition 64 of 32 samples have been aligned.
The peaks in transition 65 of 32 samples have been aligned.
The peaks in transition 66 of 32 samples have been aligned.
The peaks in transition 67 of 32 samples have been aligned.
The peaks in transition 68 of 32 samples have been aligned.
The peaks in transition 69 of 32 samples have been aligned.
The peaks in transition 70 of 32 samples have been aligned.
The peaks in transition 71 of 32 samples have been aligned.
The peaks in transition 72 of 32 samples have been aligned.
The peaks in transition 73 of 32 samples have been aligned.
The peaks in transition 74 of 32 samples have been aligned.
The peaks in transition 75 of 32 samples have been aligned.
The peaks in transition 76 of 32 samples have been aligned.
The peaks in transition 77 of 32 samples have been aligned.
The peaks in transition 78 of 32 samples have been aligned.
The peaks in transition 79 of 32 samples have been aligned.
The peaks in transition 80 of 32 samples have been aligned.
The peaks in transition 81 of 32 samples have been aligned.
The peaks in transition 82 of 32 samples have been aligned.
The peaks in transition 83 of 32 samples have been aligned.
The peaks in transition 84 of 32 samples have been aligned.
The peaks in transition 85 of 32 samples have been aligned.
The peaks in transition 86 of 32 samples have been aligned.
The peaks in transition 87 of 32 samples have been aligned.
The peaks in transition 88 of 32 samples have been aligned.
The peaks in transition 89 of 32 samples have been aligned.
The peaks in transition 90 of 32 samples have been aligned.
The peaks in transition 91 of 32 samples have been aligned.
The peaks in transition 92 of 32 samples have been aligned.
The peaks in transition 93 of 32 samples have been aligned.
The peaks in transition 94 of 32 samples have been aligned.
The peaks in transition 95 of 32 samples have been aligned.
The peaks in transition 96 of 32 samples have been aligned.
The peaks in transition 97 of 32 samples have been aligned.
The peaks in transition 98 of 32 samples have been aligned.
The peaks in transition 99 of 32 samples have been aligned.
The peaks in transition 100 of 32 samples have been aligned.
The peaks in transition 101 of 32 samples have been aligned.
The peaks in transition 102 of 32 samples have been aligned.
The peaks in transition 103 of 32 samples have been aligned.
The peaks in transition 104 of 32 samples have been aligned.
The peaks in transition 105 of 32 samples have been aligned.
The peaks in transition 106 of 32 samples have been aligned.
The peaks in transition 107 of 32 samples have been aligned.
The peaks in transition 108 of 32 samples have been aligned.
The peaks in transition 109 of 32 samples have been aligned.
The peaks in transition 110 of 32 samples have been aligned.
The peaks in transition 111 of 32 samples have been aligned.
The peaks in transition 112 of 32 samples have been aligned.
The peaks in transition 113 of 32 samples have been aligned.
The peaks in transition 114 of 32 samples have been aligned.
The peaks in transition 115 of 32 samples have been aligned.
The peaks in transition 116 of 32 samples have been aligned.
The peaks in transition 117 of 32 samples have been aligned.
The peaks in transition 118 of 32 samples have been aligned.
The peaks in transition 119 of 32 samples have been aligned.
The peaks in transition 120 of 32 samples have been aligned.
The peaks in transition 121 of 32 samples have been aligned.
The peaks in transition 122 of 32 samples have been aligned.
The peaks in transition 123 of 32 samples have been aligned.
The peaks in transition 124 of 32 samples have been aligned.
The peaks in transition 125 of 32 samples have been aligned.
The peaks in transition 126 of 32 samples have been aligned.
The peaks in transition 127 of 32 samples have been aligned.
The peaks in transition 128 of 32 samples have been aligned.
The peaks in transition 129 of 32 samples have been aligned.
The peaks in transition 130 of 32 samples have been aligned.
The peaks in transition 131 of 32 samples have been aligned.
The peaks in transition 132 of 32 samples have been aligned.
The peaks in transition 133 of 32 samples have been aligned.
The peaks in transition 134 of 32 samples have been aligned.
The peaks in transition 135 of 32 samples have been aligned.
The peaks in transition 136 of 32 samples have been aligned.
The peaks in transition 137 of 32 samples have been aligned.
The peaks in transition 138 of 32 samples have been aligned.
The peaks in transition 139 of 32 samples have been aligned.
The peaks in transition 140 of 32 samples have been aligned.
The peaks in transition 141 of 32 samples have been aligned.
The peaks in transition 142 of 32 samples have been aligned.
The peaks in transition 143 of 32 samples have been aligned.
The peaks in transition 144 of 32 samples have been aligned.
The peaks in transition 145 of 32 samples have been aligned.
The peaks in transition 146 of 32 samples have been aligned.
The peaks in transition 147 of 32 samples have been aligned.
The peaks in transition 148 of 32 samples have been aligned.
The peaks in transition 149 of 32 samples have been aligned.
The peaks in transition 150 of 32 samples have been aligned.
The peaks in transition 151 of 32 samples have been aligned.
The peaks in transition 152 of 32 samples have been aligned.
The peaks in transition 153 of 32 samples have been aligned.
The peaks in transition 154 of 32 samples have been aligned.
The peaks in transition 155 of 32 samples have been aligned.
The peaks in transition 156 of 32 samples have been aligned.
The peaks in transition 157 of 32 samples have been aligned.
The peaks in transition 158 of 32 samples have been aligned.
The peaks in transition 159 of 32 samples have been aligned.
The peaks in transition 160 of 32 samples have been aligned.
The peaks in transition 161 of 32 samples have been aligned.
The peaks in transition 162 of 32 samples have been aligned.
The peaks in transition 163 of 32 samples have been aligned.
The peaks in transition 164 of 32 samples have been aligned.
The peaks in transition 165 of 32 samples have been aligned.
The peaks in transition 166 of 32 samples have been aligned.
The peaks in transition 167 of 32 samples have been aligned.
The peaks in transition 168 of 32 samples have been aligned.
The peaks in transition 169 of 32 samples have been aligned.
The peaks in transition 170 of 32 samples have been aligned.
The peaks in transition 171 of 32 samples have been aligned.
The peaks in transition 172 of 32 samples have been aligned.
The peaks in transition 173 of 32 samples have been aligned.
The peaks in transition 174 of 32 samples have been aligned.
The peaks in transition 175 of 32 samples have been aligned.
The peaks in transition 176 of 32 samples have been aligned.
The peaks in transition 177 of 32 samples have been aligned.
The peaks in transition 178 of 32 samples have been aligned.
The peaks in transition 179 of 32 samples have been aligned.
The peaks in transition 180 of 32 samples have been aligned.
The peaks in transition 181 of 32 samples have been aligned.
The peaks in transition 182 of 32 samples have been aligned.
The peaks in transition 183 of 32 samples have been aligned.
The peaks in transition 184 of 32 samples have been aligned.
The peaks in transition 185 of 32 samples have been aligned.
The peaks in transition 186 of 32 samples have been aligned.
The peaks in transition 187 of 32 samples have been aligned.
The peaks in transition 188 of 32 samples have been aligned.
The peaks in transition 189 of 32 samples have been aligned.
The peaks in transition 190 of 32 samples have been aligned.
The peaks in transition 191 of 32 samples have been aligned.
The peaks in transition 192 of 32 samples have been aligned.
The peaks in transition 193 of 32 samples have been aligned.
The peaks in transition 194 of 32 samples have been aligned.
The peaks in transition 195 of 32 samples have been aligned.
The peaks in transition 196 of 32 samples have been aligned.
The peaks in transition 197 of 32 samples have been aligned.
The peaks in transition 198 of 32 samples have been aligned.
The peaks in transition 199 of 32 samples have been aligned.
The peaks in transition 200 of 32 samples have been aligned.
The peaks in transition 201 of 32 samples have been aligned.
The peaks in transition 202 of 32 samples have been aligned.
The peaks in transition 203 of 32 samples have been aligned.
The peaks in transition 204 of 32 samples have been aligned.
The peaks in transition 205 of 32 samples have been aligned.
The peaks in transition 206 of 32 samples have been aligned.
The peaks in transition 207 of 32 samples have been aligned.
The peaks in transition 208 of 32 samples have been aligned.
The peaks in transition 209 of 32 samples have been aligned.
The peaks in transition 210 of 32 samples have been aligned.
The peaks in transition 211 of 32 samples have been aligned.
The peaks in transition 212 of 32 samples have been aligned.
The peaks in transition 213 of 32 samples have been aligned.
The peaks in transition 214 of 32 samples have been aligned.
The peaks in transition 215 of 32 samples have been aligned.
The peaks in transition 216 of 32 samples have been aligned.
The peaks in transition 217 of 32 samples have been aligned.
The peaks in transition 218 of 32 samples have been aligned.
The peaks in transition 219 of 32 samples have been aligned.
The peaks in transition 220 of 32 samples have been aligned.
The peaks in transition 221 of 32 samples have been aligned.
The peaks in transition 222 of 32 samples have been aligned.
The peaks in transition 223 of 32 samples have been aligned.
The peaks in transition 224 of 32 samples have been aligned.
The peaks in transition 225 of 32 samples have been aligned.
The peaks in transition 226 of 32 samples have been aligned.
The peaks in transition 227 of 32 samples have been aligned.
The peaks in transition 228 of 32 samples have been aligned.
The peaks in transition 229 of 32 samples have been aligned.
The peaks in transition 230 of 32 samples have been aligned.
The peaks in transition 231 of 32 samples have been aligned.
The peaks in transition 232 of 32 samples have been aligned.
The peaks in transition 233 of 32 samples have been aligned.
The peaks in transition 234 of 32 samples have been aligned.
The peaks in transition 235 of 32 samples have been aligned.
The peaks in transition 236 of 32 samples have been aligned.
The peaks in transition 237 of 32 samples have been aligned.
The peaks in transition 238 of 32 samples have been aligned.
The peaks in transition 239 of 32 samples have been aligned.
The peaks in transition 240 of 32 samples have been aligned.
The peaks in transition 241 of 32 samples have been aligned.
The peaks in transition 242 of 32 samples have been aligned.
The peaks in transition 243 of 32 samples have been aligned.
The peaks in transition 244 of 32 samples have been aligned.
The peaks in transition 245 of 32 samples have been aligned.
The peaks in transition 246 of 32 samples have been aligned.
The peaks in transition 247 of 32 samples have been aligned.
The peaks in transition 248 of 32 samples have been aligned.
The peaks in transition 249 of 32 samples have been aligned.
The peaks in transition 250 of 32 samples have been aligned.
The peaks in transition 251 of 32 samples have been aligned.
The peaks in transition 252 of 32 samples have been aligned.
The peaks in transition 253 of 32 samples have been aligned.
The peaks in transition 254 of 32 samples have been aligned.
The peaks in transition 255 of 32 samples have been aligned.
The peaks in transition 256 of 32 samples have been aligned.
The peaks in transition 257 of 32 samples have been aligned.
The peaks in transition 258 of 32 samples have been aligned.
The peaks in transition 259 of 32 samples have been aligned.
The peaks in transition 260 of 32 samples have been aligned.
The peaks in transition 261 of 32 samples have been aligned.
The peaks in transition 262 of 32 samples have been aligned.
The peaks in transition 263 of 32 samples have been aligned.
The peaks in transition 264 of 32 samples have been aligned.
The peaks in transition 265 of 32 samples have been aligned.
Function 5 is completed.

In [19]:
aligned_dfs

                  index  1_time  ...    32_area  32_time_4markers
Transition Label                 ...
0          A          0   10.88  ...  6642411.0         12.628924
1          A          0   11.13  ...  2675259.0         12.810091
           B          1     NaN  ...   104233.0         14.011729
2          A          0    5.55  ...    44876.0          5.779977
3          A          0   10.63  ...   290774.0         11.905808
...                 ...     ...  ...        ...               ...
264        A          0     NaN  ...        NaN               NaN
           B          0     NaN  ...        NaN               NaN
265        A          0     NaN  ...        NaN               NaN
           B          1     NaN  ...        NaN               NaN
           C          2     NaN  ...   371400.0         26.911170

[777 rows x 97 columns]

In [20]:
print(aligned_dfs)
aligned_dfs.to_csv('aligned_dfs.csv')

                  index  1_time  ...    32_area  32_time_4markers
Transition Label                 ...
0          A          0   10.88  ...  6642411.0         12.628924
1          A          0   11.13  ...  2675259.0         12.810091
           B          1     NaN  ...   104233.0         14.011729
2          A          0    5.55  ...    44876.0          5.779977
3          A          0   10.63  ...   290774.0         11.905808
...                 ...     ...  ...        ...               ...
264        A          0     NaN  ...        NaN               NaN
           B          0     NaN  ...        NaN               NaN
265        A          0     NaN  ...        NaN               NaN
           B          1     NaN  ...        NaN               NaN
           C          2     NaN  ...   371400.0         26.911170

[777 rows x 97 columns]

In [21]:
#Return n_time and n_time_4markers of the peaks between marker 2 and 3
def selected_peaks_inIntermediatePhase(dfs,m2_transition,m3_transition):
    num=int(dfs.shape[1]/3)

    #To avoid modifying input parameter
    dfs_inIntermediatePhase=dfs.copy()
    for i in range(1,num+1):
        dfs_inIntermediatePhase[str(i)+'_time']=dfs_inIntermediatePhase[str(i)+'_time_4markers']
        dfs_inIntermediatePhase=dfs_inIntermediatePhase.drop(str(i)+'_area',axis='columns')

    #With a duplicate of corrected time, the calculated average and std do not change
    dfs_inIntermediatePhase['Average_MT']=dfs_inIntermediatePhase.mean(axis=1)
    dfs_inIntermediatePhase['std']=dfs_inIntermediatePhase.drop('Average_MT',axis='columns').std(axis=1,ddof=0)
    dfs_inIntermediatePhase['RSD(%)']=dfs_inIntermediatePhase['std']/dfs_inIntermediatePhase['Average_MT']*100
    dfs_inIntermediatePhase=dfs_inIntermediatePhase.drop(['std'],axis=1)

    for i in range(1,num+1):
        dfs_inIntermediatePhase[str(i)+'_time']=dfs[str(i)+'_time']

    dfs_inIntermediatePhase=dfs_inIntermediatePhase.sort_values(by='Average_MT').reset_index().set_index(['Transition'])
    dfs_inIntermediatePhase=dfs_inIntermediatePhase.loc[(dfs_inIntermediatePhase['Average_MT']>=dfs_inIntermediatePhase['Average_MT'][m2_transition])&\
    (dfs_inIntermediatePhase['Average_MT']<=dfs_inIntermediatePhase['Average_MT'][m3_transition])]
    dfs_inIntermediatePhase=dfs_inIntermediatePhase.reset_index().set_index(['Transition','Label'])
    return dfs_inIntermediatePhase

In [22]:
priorToRealign_dfs_inIntermediatePhase=selected_peaks_inIntermediatePhase(aligned_dfs,m2_transition,m3_transition)
priorToRealign_dfs_inIntermediatePhase

                  index  1_time  ...  Average_MT     RSD(%)
Transition Label                 ...
24         A          0   12.03  ...   13.576923  12.500000
86         B          0   12.22  ...   13.643226  12.533840
259        D          0     NaN  ...   13.700707  70.710678
103        C          0     NaN  ...   13.865316  18.272884
160        C          0     NaN  ...   13.901997  50.191645
...                 ...     ...  ...         ...        ...
85         D          0     NaN  ...   23.368793  18.458005
219        B          0     NaN  ...   23.394418  35.356046
123        D          3     NaN  ...   23.419792  61.652868
61         C          0     NaN  ...   23.544838  40.825082
182        A          0   21.35  ...   23.545538  12.500000

[254 rows x 67 columns]

In [23]:
print(priorToRealign_dfs_inIntermediatePhase)
priorToRealign_dfs_inIntermediatePhase.to_csv('priorToRealign_dfs_inIntermediatePhase.csv')

                  index  1_time  ...  Average_MT     RSD(%)
Transition Label                 ...
24         A          0   12.03  ...   13.576923  12.500000
86         B          0   12.22  ...   13.643226  12.533840
259        D          0     NaN  ...   13.700707  70.710678
103        C          0     NaN  ...   13.865316  18.272884
160        C          0     NaN  ...   13.901997  50.191645
...                 ...     ...  ...         ...        ...
85         D          0     NaN  ...   23.368793  18.458005
219        B          0     NaN  ...   23.394418  35.356046
123        D          3     NaN  ...   23.419792  61.652868
61         C          0     NaN  ...   23.544838  40.825082
182        A          0   21.35  ...   23.545538  12.500000

[254 rows x 67 columns]

In [24]:
# Function 6
# Suggest the potential migration time markers in intermediate phase 
# based on one condition: this analyte can be found in all samples
def find_markers_inIntermediatePhase(dfs_inIntermediatePhase_input,chart_from_idx_to_transition_and_label_inIntermediatePhase,m2_transition,m3_transition):

    #To avoid modifying input parameter
    dfs_inIntermediatePhase=dfs_inIntermediatePhase_input.copy()

    #Select m2_idx and m3_idx representing peak in m2_transition and m3_transition (its label must be 'A')
    m2_idx=transition_and_label_to_idx(chart_from_idx_to_transition_and_label_inIntermediatePhase,m2_transition,'A')
    m3_idx=transition_and_label_to_idx(chart_from_idx_to_transition_and_label_inIntermediatePhase,m3_transition,'A')
    if m2_idx==-1 or m3_idx==-1:
        return

    #Rename columns to temporarily fit in with function2
    for i in range(1,len(dfs_inIntermediatePhase)+1):
        dfs_inIntermediatePhase[i]=dfs_inIntermediatePhase[i].drop(columns=['Transition','Label']).rename_axis('Transition',axis='rows').reset_index()#possible danger: label may be dropped

    #Find potential markers, replace temporary variable 'idx' and print
    potential_markers_inIntermediatePhase=F2_find_markers(dfs_inIntermediatePhase,False)
    potential_markers_inIntermediatePhase=potential_markers_inIntermediatePhase.reset_index(drop=True)
    potential_markers_inIntermediatePhase=potential_markers_inIntermediatePhase.rename(columns={'Transition':'idx'})
    potential_markers_inIntermediatePhase['Transition']=\
        chart_from_idx_to_transition_and_label_inIntermediatePhase['Transition'][potential_markers_inIntermediatePhase['idx']].reset_index(drop=True)
    potential_markers_inIntermediatePhase['Label']=\
        chart_from_idx_to_transition_and_label_inIntermediatePhase['Label'][potential_markers_inIntermediatePhase['idx']].reset_index(drop=True)
    potential_markers_inIntermediatePhase=\
        potential_markers_inIntermediatePhase.set_index('idx')
    cols=potential_markers_inIntermediatePhase.columns.tolist()
    cols=cols[-2:]+cols[:-2]
    potential_markers_inIntermediatePhase=potential_markers_inIntermediatePhase[cols]
    print('Migration time markers for intermediate phase may be selected from the following table:')
    print('')
    print(potential_markers_inIntermediatePhase.set_index(['Transition','Label'],drop=True))
    return potential_markers_inIntermediatePhase

#Further correct the migration time between marker 2 and marker 3
#There should be only single peak in m2_transition and m3_transiton, respectively
def correcting_by4markers_byEnumeration_inIntermediatePhase(dfs,chart_from_idx_to_transition_and_label_inIntermediatePhase,\
    potential_markers_inIntermediatePhase,m2_transition,m3_transition):

    #Select m2_idx and m3_idx representing peak in m2_transition and m3_transition (its label must be 'A')
    m2_idx=transition_and_label_to_idx(chart_from_idx_to_transition_and_label_inIntermediatePhase,m2_transition,'A')
    m3_idx=transition_and_label_to_idx(chart_from_idx_to_transition_and_label_inIntermediatePhase,m3_transition,'A')
    if m2_idx==-1 or m3_idx==-1:
        return

    #Count the loops for enumeration to show progress later in real time
    cnt0=0
    for n1_idx in potential_markers_inIntermediatePhase.index:
        if n1_idx in [m2_idx,m3_idx]:
            continue
        for n2_idx in potential_markers_inIntermediatePhase.index:
            if n2_idx in [m2_idx,n1_idx,m3_idx]:
                continue
            if potential_markers_inIntermediatePhase['Average_MT'][n1_idx]>=potential_markers_inIntermediatePhase['Average_MT'][n2_idx]:
                continue
            cnt0+=1
    print(str(cnt0)+' loops will be run for enumeration')

    #Enumerate
    cnt=0
    min_avg_rsd=2**31
    best_corrected_dfs=None
    best_idx2=0
    best_idx3=0

    for n1_idx in potential_markers_inIntermediatePhase.index:
        if n1_idx in [m2_idx,m3_idx]:
            continue
        for n2_idx in potential_markers_inIntermediatePhase.index:
            if n2_idx in [m2_idx,n1_idx,m3_idx]:
                continue
            if potential_markers_inIntermediatePhase['Average_MT'][n1_idx]>=potential_markers_inIntermediatePhase['Average_MT'][n2_idx]:
                continue
            print()
            cnt+=1
            print('Progress: '+str(cnt)+'/'+str(cnt0))
            print('Select these peaks as markers: '+\
                str(m2_transition)+'A, '+\
                str(chart_from_idx_to_transition_and_label_inIntermediatePhase['Transition'][n1_idx])+\
                chart_from_idx_to_transition_and_label_inIntermediatePhase['Label'][n1_idx]+', '+\
                str(chart_from_idx_to_transition_and_label_inIntermediatePhase['Transition'][n2_idx])+\
                chart_from_idx_to_transition_and_label_inIntermediatePhase['Label'][n2_idx]+', '+\
                str(m3_transition)+'A')
            
            going_to_continue=False
            for i in range(1,len(dfs)+1):
                if potential_markers_inIntermediatePhase[str(i)+'_time'][m2_idx]>potential_markers_inIntermediatePhase[str(i)+'_time'][n1_idx]:
                    print('In sample '+str(i)+', the MT of M2 is greater than N1, migration time cannot be corrected by these markers')
                    going_to_continue=True
                if potential_markers_inIntermediatePhase[str(i)+'_time'][n1_idx]>potential_markers_inIntermediatePhase[str(i)+'_time'][n2_idx]:
                    print('In sample '+str(i)+', the MT of N1 is greater than N2, migration time cannot be corrected by these markers')
                    going_to_continue=True
                if potential_markers_inIntermediatePhase[str(i)+'_time'][n2_idx]>potential_markers_inIntermediatePhase[str(i)+'_time'][m3_idx]:
                    print('In sample '+str(i)+', the MT of N2 is greater than M3, migration time cannot be corrected by these markers')
                    going_to_continue=True
            if going_to_continue:
                continue
            
            #Rename columns to temporarily fit in with function2
            potential_markers_inIntermediatePhase_for_fun2=\
            potential_markers_inIntermediatePhase.drop(['Transition','Label'],axis='columns')\
                .reset_index().rename(columns={'idx':'Transition'})
            dfs_for_fun2={}
            for i in range(1,len(dfs)+1):
                dfs_for_fun2[i]=dfs[i].reset_index().drop(['Transition','Label'],axis='columns').\
                rename(columns={'idx':'Transition'})
            
            dfs_temp=correcting_by4markers(dfs_for_fun2,potential_markers_inIntermediatePhase_for_fun2,m2_idx,n1_idx,n2_idx,m3_idx,False)
            if dfs_temp==-1:
                print('Migration time cannot be corrected by these markers')
                continue
            
            for i in range(1,len(dfs)+1):
                dfs_temp[i]=dfs_temp[i].set_index('Transition',drop=True).rename_axis('idx',axis='rows')

            corrected_dfs=dfs_temp[1]
            for i in range(2,len(dfs)+1):
                corrected_dfs=corrected_dfs.join(dfs_temp[i],how='outer')

            corrected_dfs_temp=corrected_dfs.copy()
            for i in range(1,len(dfs)+1):
                corrected_dfs_temp=corrected_dfs_temp.drop([str(i)+'_time',str(i)+'_area'],axis='columns')
            corrected_dfs['Average_MT']=corrected_dfs_temp.mean(axis=1)
            corrected_dfs['std']=corrected_dfs_temp.std(axis=1,ddof=0)
            corrected_dfs['RSD(%)']=corrected_dfs['std']/corrected_dfs['Average_MT']*100
            corrected_dfs=corrected_dfs.drop(['std'], axis=1)
            corrected_dfs=corrected_dfs.reset_index(drop=False)
            corrected_dfs['Transition']=\
            chart_from_idx_to_transition_and_label_inIntermediatePhase['Transition'][corrected_dfs['idx']].reset_index(drop=True)
            corrected_dfs['Label']=\
                chart_from_idx_to_transition_and_label_inIntermediatePhase['Label'][corrected_dfs['idx']].reset_index(drop=True)
            corrected_dfs=corrected_dfs.set_index('idx')
            cols=corrected_dfs.columns.tolist()
            cols=cols[-2:]+cols[:-2]
            corrected_dfs=corrected_dfs[cols]
            avg_rsd=corrected_dfs['RSD(%)'].mean()
            print('The result of migration time correction:')
            print(corrected_dfs.set_index(['Transition','Label'],drop=True))
            print('The average value of RSD for each peak is: '+str(avg_rsd)+'%')
            if avg_rsd<min_avg_rsd:
                min_avg_rsd=avg_rsd
                best_corrected_dfs=corrected_dfs
                best_n1_idx=n1_idx
                best_n2_idx=n2_idx

    best_corrected_dfs=best_corrected_dfs.set_index(['Transition','Label'],drop=True)
    n1_transition=chart_from_idx_to_transition_and_label_inIntermediatePhase['Transition'][best_n1_idx]
    n1_label=chart_from_idx_to_transition_and_label_inIntermediatePhase['Label'][best_n1_idx]
    n2_transition=chart_from_idx_to_transition_and_label_inIntermediatePhase['Transition'][best_n2_idx]
    n2_label=chart_from_idx_to_transition_and_label_inIntermediatePhase['Label'][best_n2_idx]
    print('')
    print('The best markers for correction are '+\
        str(m2_transition)+'A, '+str(n1_transition)+n1_label+', '+str(n2_transition)+n2_label+', '+str(m3_transition)+'A')
    print('The best result of migration time correction:')
    print(best_corrected_dfs)
    print('The average value of RSD for each peak is: '+str(min_avg_rsd)+'%')
    return best_corrected_dfs,n1_transition,n1_label,n2_transition,n2_label

In [25]:
# Function 7
chart_from_idx_to_transition_and_label_inIntermediatePhase=priorToRealign_dfs_inIntermediatePhase.reset_index().loc[:,['Transition','Label']]\
    .sort_values(by=['Transition','Label']).reset_index(drop=True).rename_axis('idx', axis='rows')

#Construct variable dfs_inIntermediatePhase with columns 'Transition', 'Label', and a temporary index 'idx' which could 
#represent a combination of 'Transition' and 'Label'
dfs_inIntermediatePhase={}
for i in range(1,len(dfs)+1):
    dfs_inIntermediatePhase[i]=peaks_aligned_as_one_metabolite=pd.DataFrame({'Transition':[],'Label':[],str(i)+'_time':[],\
        str(i)+'_area':[]})
    for j in range(0,chart_from_idx_to_transition_and_label_inIntermediatePhase.shape[0]):
        new_transition=int(chart_from_idx_to_transition_and_label_inIntermediatePhase['Transition'][j])
        new_label=chart_from_idx_to_transition_and_label_inIntermediatePhase['Label'][j]
        new_peak=pd.DataFrame({'Transition':[new_transition],'Label':[new_label],\
            str(i)+'_time':[aligned_dfs[str(i)+'_time'][(new_transition,new_label)]],\
            str(i)+'_area':[aligned_dfs[str(i)+'_area'][(new_transition,new_label)]]},\
            index=[j])
        dfs_inIntermediatePhase[i]=dfs_inIntermediatePhase[i].append(new_peak)
    dfs_inIntermediatePhase[i]=dfs_inIntermediatePhase[i].rename_axis('idx',axis='rows').dropna(axis='index',how='any').astype({'Transition': 'int'})

potential_markers_inIntermediatePhase=find_markers_inIntermediatePhase(dfs_inIntermediatePhase,chart_from_idx_to_transition_and_label_inIntermediatePhase,m2_transition,m3_transition)

# In this step, variable 'priorToRealign_corrected_dfs_inIntermediatePhase' is a temporary result and it is not very
# important in the following step, but n1_transition, n1_label, n2_transition, n2_label are more important
priorToRealign_corrected_dfs_inIntermediatePhase,n1_transition,n1_label,n2_transition,n2_label=correcting_by4markers_byEnumeration_inIntermediatePhase(dfs_inIntermediatePhase,\
    chart_from_idx_to_transition_and_label_inIntermediatePhase,potential_markers_inIntermediatePhase,m2_transition,m3_transition)

All 14 one-peak transitions were selected.

No peaks are checked and removed, for variable "check_and_correct" is set as False.

Function 2 is completed.

Migration time markers for intermediate phase may be selected from the following table:

                  1_time  2_time  3_time  ...  32_time  Average_MT     RSD(%)
Transition Label                          ...
24         A       12.03   15.80   11.47  ...    14.09   13.789062   9.301386
86         B       12.22   16.15   11.47  ...    14.09   13.857812   9.449480
147        A       14.50   19.95   13.28  ...    16.24   16.553750  11.382868
206        B       18.52   23.29   17.21  ...    20.67   20.750312   7.948570
230        A       18.11   23.07   17.43  ...    21.14   20.829375   7.860998
262        A       18.55   23.38   17.96  ...    21.39   21.122188   7.653165
260        A       19.05   23.66   18.45  ...    21.76   21.452188   7.490496
258        A       18.92   23.82   18.52  ...    21.79   21.480313   7.432456
218        A       20.61   25.72   20.11  ...    23.38   23.109688   7.314794
61         B       20.73   25.62   20.36  ...    23.47   23.183125   7.104428
178        A       20.95   26.00   20.45  ...    23.63   23.372812   7.221743
210        A       20.95   25.97   20.45  ...    23.79   23.444688   7.208866
154        C       21.17   26.40   20.54  ...    23.94   23.668750   7.253803
182        A       21.35   26.65   20.89  ...    24.10   23.913438   7.393597

[14 rows x 34 columns]
66 loops will be run for enumeration

Progress: 1/66
Select these peaks as markers: 24A, 86B, 147A, 182A
In sample 6, the MT of M2 is greater than N1, migration time cannot be corrected by these markers
In sample 7, the MT of M2 is greater than N1, migration time cannot be corrected by these markers
In sample 12, the MT of M2 is greater than N1, migration time cannot be corrected by these markers
In sample 21, the MT of M2 is greater than N1, migration time cannot be corrected by these markers
In sample 24, the MT of M2 is greater than N1, migration time cannot be corrected by these markers
In sample 27, the MT of M2 is greater than N1, migration time cannot be corrected by these markers

Progress: 2/66
Select these peaks as markers: 24A, 86B, 206B, 182A
In sample 6, the MT of M2 is greater than N1, migration time cannot be corrected by these markers
In sample 7, the MT of M2 is greater than N1, migration time cannot be corrected by these markers
In sample 12, the MT of M2 is greater than N1, migration time cannot be corrected by these markers
In sample 21, the MT of M2 is greater than N1, migration time cannot be corrected by these markers
In sample 24, the MT of M2 is greater than N1, migration time cannot be corrected by these markers
In sample 27, the MT of M2 is greater than N1, migration time cannot be corrected by these markers

Progress: 3/66
Select these peaks as markers: 24A, 86B, 230A, 182A
In sample 6, the MT of M2 is greater than N1, migration time cannot be corrected by these markers
In sample 7, the MT of M2 is greater than N1, migration time cannot be corrected by these markers
In sample 12, the MT of M2 is greater than N1, migration time cannot be corrected by these markers
In sample 21, the MT of M2 is greater than N1, migration time cannot be corrected by these markers
In sample 24, the MT of M2 is greater than N1, migration time cannot be corrected by these markers
In sample 27, the MT of M2 is greater than N1, migration time cannot be corrected by these markers

Progress: 4/66
Select these peaks as markers: 24A, 86B, 262A, 182A
In sample 6, the MT of M2 is greater than N1, migration time cannot be corrected by these markers
In sample 7, the MT of M2 is greater than N1, migration time cannot be corrected by these markers
In sample 12, the MT of M2 is greater than N1, migration time cannot be corrected by these markers
In sample 21, the MT of M2 is greater than N1, migration time cannot be corrected by these markers
In sample 24, the MT of M2 is greater than N1, migration time cannot be corrected by these markers
In sample 27, the MT of M2 is greater than N1, migration time cannot be corrected by these markers

Progress: 5/66
Select these peaks as markers: 24A, 86B, 260A, 182A
In sample 6, the MT of M2 is greater than N1, migration time cannot be corrected by these markers
In sample 7, the MT of M2 is greater than N1, migration time cannot be corrected by these markers
In sample 12, the MT of M2 is greater than N1, migration time cannot be corrected by these markers
In sample 21, the MT of M2 is greater than N1, migration time cannot be corrected by these markers
In sample 24, the MT of M2 is greater than N1, migration time cannot be corrected by these markers
In sample 27, the MT of M2 is greater than N1, migration time cannot be corrected by these markers

Progress: 6/66
Select these peaks as markers: 24A, 86B, 258A, 182A
In sample 6, the MT of M2 is greater than N1, migration time cannot be corrected by these markers
In sample 7, the MT of M2 is greater than N1, migration time cannot be corrected by these markers
In sample 12, the MT of M2 is greater than N1, migration time cannot be corrected by these markers
In sample 21, the MT of M2 is greater than N1, migration time cannot be corrected by these markers
In sample 24, the MT of M2 is greater than N1, migration time cannot be corrected by these markers
In sample 27, the MT of M2 is greater than N1, migration time cannot be corrected by these markers

Progress: 7/66
Select these peaks as markers: 24A, 86B, 218A, 182A
In sample 6, the MT of M2 is greater than N1, migration time cannot be corrected by these markers
In sample 7, the MT of M2 is greater than N1, migration time cannot be corrected by these markers
In sample 12, the MT of M2 is greater than N1, migration time cannot be corrected by these markers
In sample 21, the MT of M2 is greater than N1, migration time cannot be corrected by these markers
In sample 24, the MT of M2 is greater than N1, migration time cannot be corrected by these markers
In sample 27, the MT of M2 is greater than N1, migration time cannot be corrected by these markers

Progress: 8/66
Select these peaks as markers: 24A, 86B, 61B, 182A
In sample 6, the MT of M2 is greater than N1, migration time cannot be corrected by these markers
In sample 7, the MT of M2 is greater than N1, migration time cannot be corrected by these markers
In sample 12, the MT of M2 is greater than N1, migration time cannot be corrected by these markers
In sample 21, the MT of M2 is greater than N1, migration time cannot be corrected by these markers
In sample 24, the MT of M2 is greater than N1, migration time cannot be corrected by these markers
In sample 27, the MT of M2 is greater than N1, migration time cannot be corrected by these markers

Progress: 9/66
Select these peaks as markers: 24A, 86B, 178A, 182A
In sample 6, the MT of M2 is greater than N1, migration time cannot be corrected by these markers
In sample 7, the MT of M2 is greater than N1, migration time cannot be corrected by these markers
In sample 12, the MT of M2 is greater than N1, migration time cannot be corrected by these markers
In sample 21, the MT of M2 is greater than N1, migration time cannot be corrected by these markers
In sample 24, the MT of M2 is greater than N1, migration time cannot be corrected by these markers
In sample 27, the MT of M2 is greater than N1, migration time cannot be corrected by these markers

Progress: 10/66
Select these peaks as markers: 24A, 86B, 210A, 182A
In sample 6, the MT of M2 is greater than N1, migration time cannot be corrected by these markers
In sample 7, the MT of M2 is greater than N1, migration time cannot be corrected by these markers
In sample 12, the MT of M2 is greater than N1, migration time cannot be corrected by these markers
In sample 21, the MT of M2 is greater than N1, migration time cannot be corrected by these markers
In sample 24, the MT of M2 is greater than N1, migration time cannot be corrected by these markers
In sample 27, the MT of M2 is greater than N1, migration time cannot be corrected by these markers

Progress: 11/66
Select these peaks as markers: 24A, 86B, 154C, 182A
In sample 6, the MT of M2 is greater than N1, migration time cannot be corrected by these markers
In sample 7, the MT of M2 is greater than N1, migration time cannot be corrected by these markers
In sample 12, the MT of M2 is greater than N1, migration time cannot be corrected by these markers
In sample 21, the MT of M2 is greater than N1, migration time cannot be corrected by these markers
In sample 24, the MT of M2 is greater than N1, migration time cannot be corrected by these markers
In sample 27, the MT of M2 is greater than N1, migration time cannot be corrected by these markers

Progress: 12/66
Select these peaks as markers: 24A, 147A, 206B, 182A
The result of migration time correction:
                  1_time    1_area  ... Average_MT    RSD(%)
Transition Label                    ...
4          B         NaN       NaN  ...  29.107245  0.782787
5          E         NaN       NaN  ...  30.093317  0.000000
8          B         NaN       NaN  ...  36.409351  0.000000
13         C         NaN       NaN  ...  20.919946  0.255757
23         C         NaN       NaN  ...  30.468776  0.000000
...                  ...       ...  ...        ...       ...
259        D         NaN       NaN  ...  20.862227  0.000000
260        A       19.05  104005.0  ...  21.435658  1.078425
261        D         NaN       NaN  ...  20.611220  0.668776
262        A       18.55   86035.0  ...  21.103134  1.187291
264        B         NaN       NaN  ...  27.626746  0.000000

[254 rows x 98 columns]
The average value of RSD for each peak is: 1.290634585960036%

Progress: 13/66
Select these peaks as markers: 24A, 147A, 230A, 182A
The result of migration time correction:
                  1_time    1_area  ... Average_MT    RSD(%)
Transition Label                    ...
4          B         NaN       NaN  ...  28.510586  0.706438
5          E         NaN       NaN  ...  29.366879  0.000000
8          B         NaN       NaN  ...  33.946339  0.000000
13         C         NaN       NaN  ...  20.876216  0.741761
23         C         NaN       NaN  ...  29.689733  0.000000
...                  ...       ...  ...        ...       ...
259        D         NaN       NaN  ...  20.533459  0.000000
260        A       19.05  104005.0  ...  21.449940  0.541747
261        D         NaN       NaN  ...  20.588056  0.166978
262        A       18.55   86035.0  ...  21.119211  0.392561
264        B         NaN       NaN  ...  27.043661  0.000000

[254 rows x 98 columns]
The average value of RSD for each peak is: 1.2535577983494286%

Progress: 14/66
Select these peaks as markers: 24A, 147A, 262A, 182A
The result of migration time correction:
                  1_time    1_area  ... Average_MT        RSD(%)
Transition Label                    ...
4          B         NaN       NaN  ...  28.399071  4.948682e-01
5          E         NaN       NaN  ...  29.166662  0.000000e+00
8          B         NaN       NaN  ...  33.665279  0.000000e+00
13         C         NaN       NaN  ...  20.967817  8.428783e-01
23         C         NaN       NaN  ...  29.475417  0.000000e+00
...                  ...       ...  ...        ...           ...
259        D         NaN       NaN  ...  20.604685  0.000000e+00
260        A       19.05  104005.0  ...  21.452573  4.329187e-01
261        D         NaN       NaN  ...  20.655482  9.827961e-02
262        A       18.55   86035.0  ...  21.122187  1.681982e-14
264        B         NaN       NaN  ...  26.973402  0.000000e+00

[254 rows x 98 columns]
The average value of RSD for each peak is: 1.2941343489998671%

Progress: 15/66
Select these peaks as markers: 24A, 147A, 260A, 182A
The result of migration time correction:
                  1_time    1_area  ... Average_MT        RSD(%)
Transition Label                    ...
4          B         NaN       NaN  ...  28.461936  1.415326e+00
5          E         NaN       NaN  ...  29.544588  0.000000e+00
8          B         NaN       NaN  ...  33.712182  0.000000e+00
13         C         NaN       NaN  ...  20.954494  8.000960e-01
23         C         NaN       NaN  ...  29.880099  0.000000e+00
...                  ...       ...  ...        ...           ...
259        D         NaN       NaN  ...  20.614841  0.000000e+00
260        A       19.05  104005.0  ...  21.452188  3.312216e-14
261        D         NaN       NaN  ...  20.657767  1.880768e-01
262        A       18.55   86035.0  ...  21.113457  5.974824e-01
264        B         NaN       NaN  ...  26.985183  0.000000e+00

[254 rows x 98 columns]
The average value of RSD for each peak is: 1.3235854057168683%

Progress: 16/66
Select these peaks as markers: 24A, 147A, 258A, 182A
The result of migration time correction:
                  1_time    1_area  ... Average_MT    RSD(%)
Transition Label                    ...
4          B         NaN       NaN  ...  28.507521  0.709725
5          E         NaN       NaN  ...  29.364381  0.000000
8          B         NaN       NaN  ...  33.537360  0.000000
13         C         NaN       NaN  ...  20.979561  0.828846
23         C         NaN       NaN  ...  29.687057  0.000000
...                  ...       ...  ...        ...       ...
259        D         NaN       NaN  ...  20.616726  0.000000
260        A       19.05  104005.0  ...  21.452324  0.414553
261        D         NaN       NaN  ...  20.702313  0.276097
262        A       18.55   86035.0  ...  21.112437  0.618126
264        B         NaN       NaN  ...  26.941158  0.000000

[254 rows x 98 columns]
The average value of RSD for each peak is: 1.322845842899567%

Progress: 17/66
Select these peaks as markers: 24A, 147A, 218A, 182A
The result of migration time correction:
                  1_time    1_area  ... Average_MT    RSD(%)
Transition Label                    ...
4          B         NaN       NaN  ...  28.533364  0.637770
5          E         NaN       NaN  ...  29.370769  0.000000
8          B         NaN       NaN  ...  31.921814  0.000000
13         C         NaN       NaN  ...  21.232116  1.046810
23         C         NaN       NaN  ...  29.693898  0.000000
...                  ...       ...  ...        ...       ...
259        D         NaN       NaN  ...  20.777976  0.000000
260        A       19.05  104005.0  ...  21.441728  1.534076
261        D         NaN       NaN  ...  20.926026  0.104636
262        A       18.55   86035.0  ...  21.108622  1.779954
264        B         NaN       NaN  ...  26.518926  0.000000

[254 rows x 98 columns]
The average value of RSD for each peak is: 1.5281459867721163%

Progress: 18/66
Select these peaks as markers: 24A, 147A, 61B, 182A
The result of migration time correction:
                  1_time    1_area  ... Average_MT    RSD(%)
Transition Label                    ...
4          B         NaN       NaN  ...  27.795257  1.391379
5          E         NaN       NaN  ...  28.752356  0.000000
8          B         NaN       NaN  ...  32.121687  0.000000
13         C         NaN       NaN  ...  21.186280  0.859548
23         C         NaN       NaN  ...  29.032487  0.000000
...                  ...       ...  ...        ...       ...
259        D         NaN       NaN  ...  20.774174  0.000000
260        A       19.05  104005.0  ...  21.441784  1.432083
261        D         NaN       NaN  ...  20.893459  0.158766
262        A       18.55   86035.0  ...  21.108691  1.703454
264        B         NaN       NaN  ...  26.572720  0.000000

[254 rows x 98 columns]
The average value of RSD for each peak is: 1.4953434602225155%

Progress: 19/66
Select these peaks as markers: 24A, 147A, 178A, 182A
The result of migration time correction:
                  1_time    1_area  ... Average_MT    RSD(%)
Transition Label                    ...
4          B         NaN       NaN  ...  28.701774  1.914313
5          E         NaN       NaN  ...  29.995278  0.000000
8          B         NaN       NaN  ...  32.675286  0.000000
13         C         NaN       NaN  ...  21.230199  0.893722
23         C         NaN       NaN  ...  30.363505  0.000000
...                  ...       ...  ...        ...       ...
259        D         NaN       NaN  ...  20.800586  0.000000
260        A       19.05  104005.0  ...  21.439686  1.620169
261        D         NaN       NaN  ...  20.926038  0.235489
262        A       18.55   86035.0  ...  21.107641  1.881140
264        B         NaN       NaN  ...  26.719381  0.000000

[254 rows x 98 columns]
The average value of RSD for each peak is: 1.5070090181741707%

Progress: 20/66
Select these peaks as markers: 24A, 147A, 210A, 182A
The result of migration time correction:
                  1_time    1_area  ... Average_MT    RSD(%)
Transition Label                    ...
4          B         NaN       NaN  ...  27.849283  1.948133
5          E         NaN       NaN  ...  28.995279  0.000000
8          B         NaN       NaN  ...  31.128632  0.000000
13         C         NaN       NaN  ...  21.194532  0.958277
23         C         NaN       NaN  ...  29.292104  0.000000
...                  ...       ...  ...        ...       ...
259        D         NaN       NaN  ...  20.762072  0.000000
260        A       19.05  104005.0  ...  21.441864  1.549702
261        D         NaN       NaN  ...  20.894874  0.086694
262        A       18.55   86035.0  ...  21.108951  1.798110
264        B         NaN       NaN  ...  26.300890  0.000000

[254 rows x 98 columns]
The average value of RSD for each peak is: 1.5827072466737147%

Progress: 21/66
Select these peaks as markers: 24A, 147A, 154C, 182A
The result of migration time correction:
                  1_time    1_area  ... Average_MT    RSD(%)
Transition Label                    ...
4          B         NaN       NaN  ...  27.721265  4.900699
5          E         NaN       NaN  ...  26.666257  0.000000
8          B         NaN       NaN  ...  32.196014  0.000000
13         C         NaN       NaN  ...  21.252694  1.079975
23         C         NaN       NaN  ...  26.813440  0.000000
...                  ...       ...  ...        ...       ...
259        D         NaN       NaN  ...  20.810430  0.000000
260        A       19.05  104005.0  ...  21.441445  1.772784
261        D         NaN       NaN  ...  20.895312  0.183281
262        A       18.55   86035.0  ...  21.109375  2.002371
264        B         NaN       NaN  ...  26.592609  0.000000

[254 rows x 98 columns]
The average value of RSD for each peak is: 1.6722287488824008%

Progress: 22/66
Select these peaks as markers: 24A, 206B, 230A, 182A
In sample 1, the MT of N1 is greater than N2, migration time cannot be corrected by these markers
In sample 2, the MT of N1 is greater than N2, migration time cannot be corrected by these markers
In sample 5, the MT of N1 is greater than N2, migration time cannot be corrected by these markers
In sample 10, the MT of N1 is greater than N2, migration time cannot be corrected by these markers
In sample 13, the MT of N1 is greater than N2, migration time cannot be corrected by these markers
In sample 14, the MT of N1 is greater than N2, migration time cannot be corrected by these markers
In sample 15, the MT of N1 is greater than N2, migration time cannot be corrected by these markers
In sample 18, the MT of N1 is greater than N2, migration time cannot be corrected by these markers
In sample 19, the MT of N1 is greater than N2, migration time cannot be corrected by these markers
In sample 25, the MT of N1 is greater than N2, migration time cannot be corrected by these markers
In sample 26, the MT of N1 is greater than N2, migration time cannot be corrected by these markers

Progress: 23/66
Select these peaks as markers: 24A, 206B, 262A, 182A
In sample 25, the MT of N1 is greater than N2, migration time cannot be corrected by these markers

In [26]:
priorToRealign_corrected_dfs_inIntermediatePhase

                  1_time    1_area  ... Average_MT    RSD(%)
Transition Label                    ...
4          B         NaN       NaN  ...  28.510586  0.706438
5          E         NaN       NaN  ...  29.366879  0.000000
8          B         NaN       NaN  ...  33.946339  0.000000
13         C         NaN       NaN  ...  20.876216  0.741761
23         C         NaN       NaN  ...  29.689733  0.000000
...                  ...       ...  ...        ...       ...
259        D         NaN       NaN  ...  20.533459  0.000000
260        A       19.05  104005.0  ...  21.449940  0.541747
261        D         NaN       NaN  ...  20.588056  0.166978
262        A       18.55   86035.0  ...  21.119211  0.392561
264        B         NaN       NaN  ...  27.043661  0.000000

[254 rows x 98 columns]

In [27]:
# Using Function 7 for the final correction
# Correct the migration times by using 6 markers
# If migration times cannot be corrected by these markers due to gamma equals 0, return -1
def correcting_by6markers(dfs_input,dfs_inIntermediatePhase_input,df_std_input,df_std_inIntermediatePhase_input,chart_from_idx_to_transition_and_label_inIntermediatePhase,\
    m1_transition,m2_transition,n1_transition,n1_label,n2_transition,n2_label,m3_transition,m4_transition):

    #Select m2_idx and m3_idx representing peak in m2_transition and m3_transition (its label must be 'A')
    m2_idx=transition_and_label_to_idx(chart_from_idx_to_transition_and_label_inIntermediatePhase,m2_transition,'A')
    n1_idx=transition_and_label_to_idx(chart_from_idx_to_transition_and_label_inIntermediatePhase,n1_transition,n1_label)
    n2_idx=transition_and_label_to_idx(chart_from_idx_to_transition_and_label_inIntermediatePhase,n2_transition,n2_label)
    m3_idx=transition_and_label_to_idx(chart_from_idx_to_transition_and_label_inIntermediatePhase,m3_transition,'A')

    dfs=dfs_input.copy()
    df_std=df_std_input.copy()
    df_std_temp = df_std.set_index('Transition')

    #Temporarily fit in with function get_gamma
    dfs_inIntermediatePhase=dfs_inIntermediatePhase_input.copy()
    df_std_inIntermediatePhase=df_std_inIntermediatePhase_input.reset_index().drop(['Transition','Label'],axis='columns').\
        rename(columns={'idx':'Transition'})
    df_std_inIntermediatePhase.index+=1
    df_std_inIntermediatePhase_temp = df_std_inIntermediatePhase.set_index('Transition')

    tm1_std = df_std_temp.loc[m1_transition,'Average_MT']
    tm2_std = df_std_temp.loc[m2_transition,'Average_MT']
    tm3_std = df_std_temp.loc[m3_transition,'Average_MT']
    tn1_std = df_std_inIntermediatePhase_temp.loc[n1_idx,'Average_MT']
    tn2_std = df_std_inIntermediatePhase_temp.loc[n2_idx,'Average_MT']
    for i in range(1,len(dfs)+1):

        #Temporarily fit in with function get_gamma
        dfs_inIntermediatePhase[i]=dfs_inIntermediatePhase[i].reset_index().drop(['Transition','Label'],axis='columns').\
            rename(columns={'idx':'Transition'})

        gamma1 = get_gamma(dfs, i, df_std, m1_transition, m2_transition)
        gamma2 = get_gamma(dfs, i, df_std, m3_transition, m4_transition)
        gamma_n1 = get_gamma(dfs_inIntermediatePhase, i, df_std_inIntermediatePhase, m2_idx, n1_idx)
        gamma_n2 = get_gamma(dfs_inIntermediatePhase, i, df_std_inIntermediatePhase, n1_idx, n2_idx)
        gamma_n3 = get_gamma(dfs_inIntermediatePhase, i, df_std_inIntermediatePhase, n2_idx, m3_idx)

        if gamma1==0:
            print('Migration times cannot be corrected by m1_transition='+str(m1_transition)+\
                ' and m2_transition='+str(m2_transition)+', because their migration '+\
                'times in sample '+str(i)+' are identical.')
            return -1
        if gamma2==0:
            print('Migration times cannot be corrected by m3_transition='+str(m3_transition)+\
                  ' and m4_transition='+str(m4_transition)+', because their migration '+\
                  'times in sample '+str(i)+' are identical.')
            return -1
        if gamma_n1==0:
            print('Migration times cannot be corrected by m2_transition='+str(m2_transition)+\
                ' and n1='+str(n1_transition)+n1_label+', because their migration '+\
                'times in sample '+str(i)+' are identical.')
            return -1
        if gamma_n2==0:
            print('Migration times cannot be corrected by n1='+str(n1_transition)+n1_label+\
                ' and n2='+str(n2_transition)+n2_label+', because their migration '+\
                'times in sample '+str(i)+' are identical.')
            return -1
        if gamma_n3==0:
            print('Migration times cannot be corrected by n2='+str(n2_transition)+n2_label+\
                ' and m3_transition='+str(m3_transition)+', because their migration '+\
                'times in sample '+str(i)+' are identical.')
            return -1

        df_temp = dfs[i].set_index('Transition')
        #Replace temporary axis name by real name 'idx'
        dfs_inIntermediatePhase_temp=dfs_inIntermediatePhase[i].set_index('Transition').rename_axis('idx',axis='rows')

        tm1 = df_temp.loc[m1_transition,str(i)+'_time']
        tm2 = df_temp.loc[m2_transition,str(i)+'_time']
        tm3 = df_temp.loc[m3_transition,str(i)+'_time']
        tn1 = dfs_inIntermediatePhase_temp.loc[n1_idx,str(i)+'_time']
        tn2 = dfs_inIntermediatePhase_temp.loc[n2_idx,str(i)+'_time']
        dfs[i][str(i)+'_time_6markers']= None
        analyte_num = dfs[i].shape[0]
        for j in range(0,analyte_num):
            t_origin = dfs[i].loc[j,str(i)+'_time']
            if t_origin <= tm2:
                t_6marker = 1/((1/tm1_std)-(1/gamma1)*((1/tm1)-(1/t_origin)))
            elif t_origin <= tn1:
                t_6marker = 1/((1/tm2_std)-(1/gamma_n1)*((1/tm2)-(1/t_origin)))
            elif t_origin <= tn2:
                t_6marker = 1/((1/tn1_std)-(1/gamma_n2)*((1/tn1)-(1/t_origin)))
            elif t_origin <= tm3:
                t_6marker = 1/((1/tn2_std)-(1/gamma_n3)*((1/tn2)-(1/t_origin)))
            else:
                t_6marker = 1/((1/tm3_std)-(1/gamma2)*((1/tm3)-(1/t_origin)))
            dfs[i].loc[j,str(i)+'_time_6markers'] = t_6marker
    return dfs

In [ ]:
corrected_dfs_final=correcting_by6markers(dfs,dfs_inIntermediatePhase,potential_markers,potential_markers_inIntermediatePhase,chart_from_idx_to_transition_and_label_inIntermediatePhase,\
    m1_transition,m2_transition,n1_transition,n1_label,n2_transition,n2_label,m3_transition,m4_transition)
aligned_dfs_final=align(corrected_dfs_final,0.02,0)#aligned_dfs_final=align(corrected_dfs_final,0.025,0)

The peaks in transition 0 of 32 samples have been aligned.
The peaks in transition 1 of 32 samples have been aligned.
The peaks in transition 2 of 32 samples have been aligned.
The peaks in transition 3 of 32 samples have been aligned.
The peaks in transition 4 of 32 samples have been aligned.
The peaks in transition 5 of 32 samples have been aligned.
The peaks in transition 6 of 32 samples have been aligned.
The peaks in transition 7 of 32 samples have been aligned.
The peaks in transition 8 of 32 samples have been aligned.
The peaks in transition 9 of 32 samples have been aligned.
The peaks in transition 10 of 32 samples have been aligned.
The peaks in transition 11 of 32 samples have been aligned.
The peaks in transition 12 of 32 samples have been aligned.
The peaks in transition 13 of 32 samples have been aligned.
The peaks in transition 14 of 32 samples have been aligned.
The peaks in transition 15 of 32 samples have been aligned.
The peaks in transition 16 of 32 samples have been aligned.
The peaks in transition 17 of 32 samples have been aligned.
The peaks in transition 18 of 32 samples have been aligned.
The peaks in transition 19 of 32 samples have been aligned.
The peaks in transition 20 of 32 samples have been aligned.
The peaks in transition 21 of 32 samples have been aligned.
The peaks in transition 22 of 32 samples have been aligned.
The peaks in transition 23 of 32 samples have been aligned.
The peaks in transition 24 of 32 samples have been aligned.
The peaks in transition 25 of 32 samples have been aligned.
The peaks in transition 26 of 32 samples have been aligned.
The peaks in transition 27 of 32 samples have been aligned.
The peaks in transition 28 of 32 samples have been aligned.
The peaks in transition 29 of 32 samples have been aligned.
The peaks in transition 30 of 32 samples have been aligned.
The peaks in transition 31 of 32 samples have been aligned.
The peaks in transition 32 of 32 samples have been aligned.
The peaks in transition 33 of 32 samples have been aligned.
The peaks in transition 34 of 32 samples have been aligned.
The peaks in transition 35 of 32 samples have been aligned.
The peaks in transition 36 of 32 samples have been aligned.
The peaks in transition 37 of 32 samples have been aligned.
The peaks in transition 38 of 32 samples have been aligned.
The peaks in transition 39 of 32 samples have been aligned.
The peaks in transition 40 of 32 samples have been aligned.
The peaks in transition 41 of 32 samples have been aligned.
The peaks in transition 42 of 32 samples have been aligned.
The peaks in transition 43 of 32 samples have been aligned.
The peaks in transition 44 of 32 samples have been aligned.
The peaks in transition 45 of 32 samples have been aligned.
The peaks in transition 46 of 32 samples have been aligned.
The peaks in transition 47 of 32 samples have been aligned.
The peaks in transition 48 of 32 samples have been aligned.
The peaks in transition 49 of 32 samples have been aligned.
The peaks in transition 50 of 32 samples have been aligned.
The peaks in transition 51 of 32 samples have been aligned.
The peaks in transition 52 of 32 samples have been aligned.
The peaks in transition 53 of 32 samples have been aligned.
The peaks in transition 54 of 32 samples have been aligned.
The peaks in transition 55 of 32 samples have been aligned.
The peaks in transition 56 of 32 samples have been aligned.
The peaks in transition 57 of 32 samples have been aligned.
The peaks in transition 58 of 32 samples have been aligned.
The peaks in transition 59 of 32 samples have been aligned.
The peaks in transition 60 of 32 samples have been aligned.
The peaks in transition 61 of 32 samples have been aligned.
The peaks in transition 62 of 32 samples have been aligned.
The peaks in transition 63 of 32 samples have been aligned.
The peaks in transition 64 of 32 samples have been aligned.
The peaks in transition 65 of 32 samples have been aligned.
The peaks in transition 66 of 32 samples have been aligned.
The peaks in transition 67 of 32 samples have been aligned.
The peaks in transition 68 of 32 samples have been aligned.
The peaks in transition 69 of 32 samples have been aligned.
The peaks in transition 70 of 32 samples have been aligned.
The peaks in transition 71 of 32 samples have been aligned.
The peaks in transition 72 of 32 samples have been aligned.
The peaks in transition 73 of 32 samples have been aligned.
The peaks in transition 74 of 32 samples have been aligned.
The peaks in transition 75 of 32 samples have been aligned.
The peaks in transition 76 of 32 samples have been aligned.
The peaks in transition 77 of 32 samples have been aligned.
The peaks in transition 78 of 32 samples have been aligned.
The peaks in transition 79 of 32 samples have been aligned.
The peaks in transition 80 of 32 samples have been aligned.
The peaks in transition 81 of 32 samples have been aligned.
The peaks in transition 82 of 32 samples have been aligned.
The peaks in transition 83 of 32 samples have been aligned.
The peaks in transition 84 of 32 samples have been aligned.
The peaks in transition 85 of 32 samples have been aligned.
The peaks in transition 86 of 32 samples have been aligned.
The peaks in transition 87 of 32 samples have been aligned.
The peaks in transition 88 of 32 samples have been aligned.
The peaks in transition 89 of 32 samples have been aligned.
The peaks in transition 90 of 32 samples have been aligned.
The peaks in transition 91 of 32 samples have been aligned.
The peaks in transition 92 of 32 samples have been aligned.
The peaks in transition 93 of 32 samples have been aligned.
The peaks in transition 94 of 32 samples have been aligned.
The peaks in transition 95 of 32 samples have been aligned.
The peaks in transition 96 of 32 samples have been aligned.
The peaks in transition 97 of 32 samples have been aligned.
The peaks in transition 98 of 32 samples have been aligned.
The peaks in transition 99 of 32 samples have been aligned.
The peaks in transition 100 of 32 samples have been aligned.
The peaks in transition 101 of 32 samples have been aligned.
The peaks in transition 102 of 32 samples have been aligned.
The peaks in transition 103 of 32 samples have been aligned.
The peaks in transition 104 of 32 samples have been aligned.
The peaks in transition 105 of 32 samples have been aligned.
The peaks in transition 106 of 32 samples have been aligned.
The peaks in transition 107 of 32 samples have been aligned.
The peaks in transition 108 of 32 samples have been aligned.
The peaks in transition 109 of 32 samples have been aligned.
The peaks in transition 110 of 32 samples have been aligned.
The peaks in transition 111 of 32 samples have been aligned.
The peaks in transition 112 of 32 samples have been aligned.
The peaks in transition 113 of 32 samples have been aligned.
The peaks in transition 114 of 32 samples have been aligned.
The peaks in transition 115 of 32 samples have been aligned.
The peaks in transition 116 of 32 samples have been aligned.
The peaks in transition 117 of 32 samples have been aligned.
The peaks in transition 118 of 32 samples have been aligned.
The peaks in transition 119 of 32 samples have been aligned.
The peaks in transition 120 of 32 samples have been aligned.
The peaks in transition 121 of 32 samples have been aligned.
The peaks in transition 122 of 32 samples have been aligned.
The peaks in transition 123 of 32 samples have been aligned.
The peaks in transition 124 of 32 samples have been aligned.
The peaks in transition 125 of 32 samples have been aligned.
The peaks in transition 126 of 32 samples have been aligned.
The peaks in transition 127 of 32 samples have been aligned.
The peaks in transition 128 of 32 samples have been aligned.
The peaks in transition 129 of 32 samples have been aligned.
The peaks in transition 130 of 32 samples have been aligned.
The peaks in transition 131 of 32 samples have been aligned.
The peaks in transition 132 of 32 samples have been aligned.
The peaks in transition 133 of 32 samples have been aligned.
The peaks in transition 134 of 32 samples have been aligned.
The peaks in transition 135 of 32 samples have been aligned.
The peaks in transition 136 of 32 samples have been aligned.
The peaks in transition 137 of 32 samples have been aligned.
The peaks in transition 138 of 32 samples have been aligned.
The peaks in transition 139 of 32 samples have been aligned.
The peaks in transition 140 of 32 samples have been aligned.
The peaks in transition 141 of 32 samples have been aligned.
The peaks in transition 142 of 32 samples have been aligned.
The peaks in transition 143 of 32 samples have been aligned.
The peaks in transition 144 of 32 samples have been aligned.
The peaks in transition 145 of 32 samples have been aligned.
The peaks in transition 146 of 32 samples have been aligned.
The peaks in transition 147 of 32 samples have been aligned.
The peaks in transition 148 of 32 samples have been aligned.
The peaks in transition 149 of 32 samples have been aligned.
The peaks in transition 150 of 32 samples have been aligned.
The peaks in transition 151 of 32 samples have been aligned.
The peaks in transition 152 of 32 samples have been aligned.
The peaks in transition 153 of 32 samples have been aligned.
The peaks in transition 154 of 32 samples have been aligned.
The peaks in transition 155 of 32 samples have been aligned.
The peaks in transition 156 of 32 samples have been aligned.
The peaks in transition 157 of 32 samples have been aligned.
The peaks in transition 158 of 32 samples have been aligned.
The peaks in transition 159 of 32 samples have been aligned.
The peaks in transition 160 of 32 samples have been aligned.
The peaks in transition 161 of 32 samples have been aligned.
The peaks in transition 162 of 32 samples have been aligned.
The peaks in transition 163 of 32 samples have been aligned.
The peaks in transition 164 of 32 samples have been aligned.
The peaks in transition 165 of 32 samples have been aligned.
The peaks in transition 166 of 32 samples have been aligned.
The peaks in transition 167 of 32 samples have been aligned.
The peaks in transition 168 of 32 samples have been aligned.
The peaks in transition 169 of 32 samples have been aligned.
The peaks in transition 170 of 32 samples have been aligned.
The peaks in transition 171 of 32 samples have been aligned.
The peaks in transition 172 of 32 samples have been aligned.
The peaks in transition 173 of 32 samples have been aligned.
The peaks in transition 174 of 32 samples have been aligned.
The peaks in transition 175 of 32 samples have been aligned.
The peaks in transition 176 of 32 samples have been aligned.
The peaks in transition 177 of 32 samples have been aligned.
The peaks in transition 178 of 32 samples have been aligned.
The peaks in transition 179 of 32 samples have been aligned.
The peaks in transition 180 of 32 samples have been aligned.
The peaks in transition 181 of 32 samples have been aligned.
The peaks in transition 182 of 32 samples have been aligned.
The peaks in transition 183 of 32 samples have been aligned.
The peaks in transition 184 of 32 samples have been aligned.
The peaks in transition 185 of 32 samples have been aligned.
The peaks in transition 186 of 32 samples have been aligned.
The peaks in transition 187 of 32 samples have been aligned.
The peaks in transition 188 of 32 samples have been aligned.
The peaks in transition 189 of 32 samples have been aligned.
The peaks in transition 190 of 32 samples have been aligned.
The peaks in transition 191 of 32 samples have been aligned.
The peaks in transition 192 of 32 samples have been aligned.
The peaks in transition 193 of 32 samples have been aligned.
The peaks in transition 194 of 32 samples have been aligned.
The peaks in transition 195 of 32 samples have been aligned.
The peaks in transition 196 of 32 samples have been aligned.
The peaks in transition 197 of 32 samples have been aligned.
The peaks in transition 198 of 32 samples have been aligned.
The peaks in transition 199 of 32 samples have been aligned.
The peaks in transition 200 of 32 samples have been aligned.
The peaks in transition 201 of 32 samples have been aligned.
The peaks in transition 202 of 32 samples have been aligned.
The peaks in transition 203 of 32 samples have been aligned.
The peaks in transition 204 of 32 samples have been aligned.
The peaks in transition 205 of 32 samples have been aligned.
The peaks in transition 206 of 32 samples have been aligned.
The peaks in transition 207 of 32 samples have been aligned.
The peaks in transition 208 of 32 samples have been aligned.
The peaks in transition 209 of 32 samples have been aligned.
The peaks in transition 210 of 32 samples have been aligned.
The peaks in transition 211 of 32 samples have been aligned.
The peaks in transition 212 of 32 samples have been aligned.
The peaks in transition 213 of 32 samples have been aligned.
The peaks in transition 214 of 32 samples have been aligned.
The peaks in transition 215 of 32 samples have been aligned.
The peaks in transition 216 of 32 samples have been aligned.
The peaks in transition 217 of 32 samples have been aligned.
The peaks in transition 218 of 32 samples have been aligned.
The peaks in transition 219 of 32 samples have been aligned.
The peaks in transition 220 of 32 samples have been aligned.
The peaks in transition 221 of 32 samples have been aligned.
The peaks in transition 222 of 32 samples have been aligned.
The peaks in transition 223 of 32 samples have been aligned.
The peaks in transition 224 of 32 samples have been aligned.
The peaks in transition 225 of 32 samples have been aligned.
The peaks in transition 226 of 32 samples have been aligned.
The peaks in transition 227 of 32 samples have been aligned.
The peaks in transition 228 of 32 samples have been aligned.
The peaks in transition 229 of 32 samples have been aligned.
The peaks in transition 230 of 32 samples have been aligned.
The peaks in transition 231 of 32 samples have been aligned.
The peaks in transition 232 of 32 samples have been aligned.
The peaks in transition 233 of 32 samples have been aligned.
The peaks in transition 234 of 32 samples have been aligned.
The peaks in transition 235 of 32 samples have been aligned.
The peaks in transition 236 of 32 samples have been aligned.
The peaks in transition 237 of 32 samples have been aligned.
The peaks in transition 238 of 32 samples have been aligned.
The peaks in transition 239 of 32 samples have been aligned.
The peaks in transition 240 of 32 samples have been aligned.
The peaks in transition 241 of 32 samples have been aligned.
The peaks in transition 242 of 32 samples have been aligned.
The peaks in transition 243 of 32 samples have been aligned.
The peaks in transition 244 of 32 samples have been aligned.
The peaks in transition 245 of 32 samples have been aligned.
The peaks in transition 246 of 32 samples have been aligned.
The peaks in transition 247 of 32 samples have been aligned.
The peaks in transition 248 of 32 samples have been aligned.
The peaks in transition 249 of 32 samples have been aligned.

In [ ]:
print(aligned_dfs_final)

In [ ]:
# Re-examination of the alignment results
aligned_dfs_final=with_avgMT_and_RSD(aligned_dfs_final)
aligned_dfs_final.to_csv('aligned_dfs_final.csv')
checked_and_corrected_dfs_without_RSD_correction,checked_and_corrected_dfs=check_and_correct(aligned_dfs_final,0.025,'step_last')
checked_and_corrected_dfs_without_RSD_correction=with_avgMT_and_RSD(checked_and_corrected_dfs_without_RSD_correction)
checked_and_corrected_dfs=with_avgMT_and_RSD(checked_and_corrected_dfs)
checked_and_corrected_dfs_without_RSD_correction.to_csv('checked_and_corrected_dfs_without_RSD_correction.csv')
checked_and_corrected_dfs.to_csv('checked_and_corrected_dfs.csv')

In [ ]:
# Check the result
print(checked_and_corrected_dfs)